In [1]:
from numpy import array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [3]:
# define input sequence
parser = (lambda x:datetime.datetime.strptime(x, '%Y.%m.%d')) 
df = pd.read_csv('sp_beaches_update.csv', parse_dates=['Date'])
df = df.sort_values(by=['Date'])
df=df.loc[~df['Enterococcus'].isnull()]
#remover a praia do Leste, da cidade de iguape, pois esta praia sumiu por erosão em 2012
#remover a Lagoa Prumirim, da cidade de Ubatuba, pois esta praia possui somente 3 medições
df = df.loc[df['Beach']!='DO LESTE'].loc[df['Beach']!='LAGOA PRUMIRIM']
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 69016 entries, 0 to 66721
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          69016 non-null  object
 1   Beach         69016 non-null  object
 2   Date          69016 non-null  datetime64[ns]
 3   Enterococcus  69016 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 2.6+ MB

In [4]:
df.loc[df['City']=='UBATUBA'].loc[df['Beach']=='PULSO']

          City  Beach       Date  Enterococcus
8303   UBATUBA  PULSO 2012-01-03             1
8304   UBATUBA  PULSO 2012-02-05             1
8305   UBATUBA  PULSO 2012-03-04             1
8306   UBATUBA  PULSO 2012-04-01             1
8307   UBATUBA  PULSO 2012-05-06             2
...        ...    ...        ...           ...
66655  UBATUBA  PULSO 2019-11-03            27
66656  UBATUBA  PULSO 2019-12-01            42
69027  UBATUBA  PULSO 2020-01-05             7
69028  UBATUBA  PULSO 2020-02-02             1
69029  UBATUBA  PULSO 2020-03-01             5

[96 rows x 4 columns]

In [5]:
# selecionar praias com medições mensais
df2 = df.loc[df['City']=='GUARUJÁ'].loc[df['Beach']=='IPORANGA'] #75 linhas
df2 = df2.append(df.loc[df['City']=='IGUAPE'].loc[df['Beach']=='JURÉIA'])#105 linhas
df2 = df2.append(df.loc[df['City']=='ILHA COMPRIDA'].loc[df['Beach']=='BALNEÁRIO ADRIANA'])#94 linhas
df2 = df2.append(df.loc[df['City']=='ILHA COMPRIDA'].loc[df['Beach']=='CENTRO'])#102 Linhas
df2 = df2.append(df.loc[df['City']=='ILHA COMPRIDA'].loc[df['Beach']=='PONTAL'])#102 linhas
df2 = df2.append(df.loc[df['City']=='ILHA COMPRIDA'].loc[df['Beach']=='PRAINHA (BALSA)'])#102 Linhas
df2 = df2.append(df.loc[df['City']=='UBATUBA'].loc[df['Beach']=='PRUMIRIM'])#97 linhas
df2 = df2.append(df.loc[df['City']=='UBATUBA'].loc[df['Beach']=='PULSO'])#96 Linhas
df2

          City     Beach       Date  Enterococcus
16688  GUARUJÁ  IPORANGA 2014-01-05           133
16689  GUARUJÁ  IPORANGA 2014-02-02            45
16690  GUARUJÁ  IPORANGA 2014-03-02             1
16691  GUARUJÁ  IPORANGA 2014-04-06             1
16692  GUARUJÁ  IPORANGA 2014-05-04             1
...        ...       ...        ...           ...
66655  UBATUBA     PULSO 2019-11-03            27
66656  UBATUBA     PULSO 2019-12-01            42
69027  UBATUBA     PULSO 2020-01-05             7
69028  UBATUBA     PULSO 2020-02-02             1
69029  UBATUBA     PULSO 2020-03-01             5

[770 rows x 4 columns]

In [6]:
n_steps = 4
for cidade in df2.City.unique():
    #print(df2.loc[df2['City']==cidade].Beach.unique())
    for praia in df2.loc[df2['City']==cidade].Beach.unique():
        #print(praia)
        df_beach = df.loc[df['City']==cidade].loc[df['Beach']==praia][['Date','Enterococcus']]
        df_beach.columns = ['ds', 'y']
        df_beach.set_index('ds', inplace=True)
        X, y = split_sequence(df_beach.values, n_steps)
        n_features = 1
        X = X.reshape((X.shape[0], X.shape[1], n_features))
        model = Sequential()
        model.add(LSTM(104, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
        model.add(LSTM(104, activation='relu'))
        model.add(Dense(1))
        model.compile(optimizer='adam', loss='mse')
        with tf.device('/GPU:0'): 
            R = model.fit(X, y, epochs=200, verbose=1)
        loss=round(R.history['loss'][-1])
        model.save('model'+cidade+'-'+praia+'-'+str(loss)+'.h5')
        print(cidade+'-'+praia+'-'+str(loss))

Train on 71 samples
Epoch 1/200
71/71 [==============================] - 2s 28ms/sample - loss: 799.8286
Epoch 2/200
71/71 [==============================] - 0s 330us/sample - loss: 754.8524
Epoch 3/200
71/71 [==============================] - 0s 351us/sample - loss: 723.3947
Epoch 4/200
71/71 [==============================] - 0s 351us/sample - loss: 724.9940
Epoch 5/200
71/71 [==============================] - 0s 365us/sample - loss: 702.5327
Epoch 6/200
71/71 [==============================] - 0s 367us/sample - loss: 681.2958
Epoch 7/200
71/71 [==============================] - 0s 379us/sample - loss: 669.5022
Epoch 8/200
71/71 [==============================] - 0s 351us/sample - loss: 660.2432
Epoch 9/200
71/71 [==============================] - 0s 337us/sample - loss: 645.6356
Epoch 10/200
71/71 [==============================] - 0s 344us/sample - loss: 627.6371
Epoch 11/200
71/71 [==============================] - 0s 337us/sample - loss: 608.0033
Epoch 12/200
71/71 [==============================] - 0s 337us/sample - loss: 587.7008
Epoch 13/200
71/71 [==============================] - 0s 323us/sample - loss: 568.4820
Epoch 14/200
71/71 [==============================] - 0s 337us/sample - loss: 551.6627
Epoch 15/200
71/71 [==============================] - 0s 365us/sample - loss: 534.4014
Epoch 16/200
71/71 [==============================] - 0s 340us/sample - loss: 518.3099
Epoch 17/200
71/71 [==============================] - 0s 351us/sample - loss: 506.2211
Epoch 18/200
71/71 [==============================] - 0s 393us/sample - loss: 498.6099
Epoch 19/200
71/71 [==============================] - 0s 379us/sample - loss: 492.9775
Epoch 20/200
71/71 [==============================] - 0s 337us/sample - loss: 497.7396
Epoch 21/200
71/71 [==============================] - 0s 351us/sample - loss: 482.9005
Epoch 22/200
71/71 [==============================] - 0s 337us/sample - loss: 472.2674
Epoch 23/200
71/71 [==============================] - 0s 407us/sample - loss: 470.4718
Epoch 24/200
71/71 [==============================] - 0s 379us/sample - loss: 464.2057
Epoch 25/200
71/71 [==============================] - 0s 365us/sample - loss: 457.8588
Epoch 26/200
71/71 [==============================] - 0s 351us/sample - loss: 454.5311
Epoch 27/200
71/71 [==============================] - 0s 358us/sample - loss: 452.0069
Epoch 28/200
71/71 [==============================] - 0s 337us/sample - loss: 443.2265
Epoch 29/200
71/71 [==============================] - 0s 337us/sample - loss: 452.7032
Epoch 30/200
71/71 [==============================] - 0s 393us/sample - loss: 451.0969
Epoch 31/200
71/71 [==============================] - 0s 323us/sample - loss: 437.9956
Epoch 32/200
71/71 [==============================] - 0s 351us/sample - loss: 439.9571
Epoch 33/200
71/71 [==============================] - 0s 337us/sample - loss: 451.7650
Epoch 34/200
71/71 [==============================] - 0s 351us/sample - loss: 452.5999
Epoch 35/200
71/71 [==============================] - 0s 379us/sample - loss: 423.0397
Epoch 36/200
71/71 [==============================] - 0s 323us/sample - loss: 434.1152
Epoch 37/200
71/71 [==============================] - 0s 337us/sample - loss: 442.4583
Epoch 38/200
71/71 [==============================] - 0s 365us/sample - loss: 433.5387
Epoch 39/200
71/71 [==============================] - 0s 351us/sample - loss: 417.6304
Epoch 40/200
71/71 [==============================] - 0s 337us/sample - loss: 411.4738
Epoch 41/200
71/71 [==============================] - 0s 365us/sample - loss: 413.4222
Epoch 42/200
71/71 [==============================] - 0s 393us/sample - loss: 405.5640
Epoch 43/200
71/71 [==============================] - 0s 351us/sample - loss: 399.4611
Epoch 44/200
71/71 [==============================] - 0s 351us/sample - loss: 403.1317
Epoch 45/200
71/71 [==============================] - 0s 365us/sample - loss: 395.5082
Epoch 46/200
71/71 [==============================] - 0s 365us/sample - loss: 394.9058
Epoch 47/200
71/71 [==============================] - 0s 379us/sample - loss: 397.7929
Epoch 48/200
71/71 [==============================] - 0s 365us/sample - loss: 369.6207
Epoch 49/200
71/71 [==============================] - 0s 387us/sample - loss: 387.9065
Epoch 50/200
71/71 [==============================] - 0s 351us/sample - loss: 384.0560
Epoch 51/200
71/71 [==============================] - 0s 323us/sample - loss: 377.6471
Epoch 52/200
71/71 [==============================] - 0s 351us/sample - loss: 366.0108
Epoch 53/200
71/71 [==============================] - 0s 365us/sample - loss: 349.1961
Epoch 54/200
71/71 [==============================] - 0s 323us/sample - loss: 365.7050
Epoch 55/200
71/71 [==============================] - 0s 323us/sample - loss: 377.0065
Epoch 56/200
71/71 [==============================] - 0s 387us/sample - loss: 349.6504
Epoch 57/200
71/71 [==============================] - 0s 337us/sample - loss: 351.8502
Epoch 58/200
71/71 [==============================] - 0s 323us/sample - loss: 376.7787
Epoch 59/200
71/71 [==============================] - 0s 323us/sample - loss: 374.1067
Epoch 60/200
71/71 [==============================] - 0s 351us/sample - loss: 354.6106
Epoch 61/200
71/71 [==============================] - 0s 379us/sample - loss: 332.8678
Epoch 62/200
71/71 [==============================] - 0s 337us/sample - loss: 398.8163
Epoch 63/200
71/71 [==============================] - 0s 365us/sample - loss: 320.8122
Epoch 64/200
71/71 [==============================] - 0s 309us/sample - loss: 322.7826
Epoch 65/200
71/71 [==============================] - 0s 359us/sample - loss: 319.7829
Epoch 66/200
71/71 [==============================] - 0s 323us/sample - loss: 313.4225
Epoch 67/200
71/71 [==============================] - 0s 337us/sample - loss: 299.7475
Epoch 68/200
71/71 [==============================] - 0s 350us/sample - loss: 288.6745
Epoch 69/200
71/71 [==============================] - 0s 351us/sample - loss: 270.2086
Epoch 70/200
71/71 [==============================] - 0s 337us/sample - loss: 266.1278
Epoch 71/200
71/71 [==============================] - 0s 337us/sample - loss: 259.1712
Epoch 72/200
71/71 [==============================] - 0s 317us/sample - loss: 245.5945
Epoch 73/200
71/71 [==============================] - 0s 351us/sample - loss: 234.9064
Epoch 74/200
71/71 [==============================] - 0s 323us/sample - loss: 228.9735
Epoch 75/200
71/71 [==============================] - 0s 323us/sample - loss: 222.6015
Epoch 76/200
71/71 [==============================] - 0s 351us/sample - loss: 211.1918
Epoch 77/200
71/71 [==============================] - 0s 351us/sample - loss: 215.7627
Epoch 78/200
71/71 [==============================] - 0s 365us/sample - loss: 291.8713
Epoch 79/200
71/71 [==============================] - 0s 323us/sample - loss: 274.3654
Epoch 80/200
71/71 [==============================] - 0s 337us/sample - loss: 250.5296
Epoch 81/200
71/71 [==============================] - 0s 337us/sample - loss: 245.3589
Epoch 82/200
71/71 [==============================] - 0s 337us/sample - loss: 239.6723
Epoch 83/200
71/71 [==============================] - 0s 337us/sample - loss: 238.1961
Epoch 84/200
71/71 [==============================] - 0s 323us/sample - loss: 225.5792
Epoch 85/200
71/71 [==============================] - 0s 352us/sample - loss: 218.1462
Epoch 86/200
71/71 [==============================] - 0s 337us/sample - loss: 216.1515
Epoch 87/200
71/71 [==============================] - 0s 365us/sample - loss: 206.6404
Epoch 88/200
71/71 [==============================] - 0s 337us/sample - loss: 208.1427
Epoch 89/200
71/71 [==============================] - 0s 323us/sample - loss: 193.4794
Epoch 90/200
71/71 [==============================] - 0s 337us/sample - loss: 203.1468
Epoch 91/200
71/71 [==============================] - 0s 309us/sample - loss: 199.2800
Epoch 92/200
71/71 [==============================] - 0s 323us/sample - loss: 193.5921
Epoch 93/200
71/71 [==============================] - 0s 351us/sample - loss: 189.6295
Epoch 94/200
71/71 [==============================] - 0s 365us/sample - loss: 188.9906
Epoch 95/200

71/71 [==============================] - 0s 337us/sample - loss: 189.7604
Epoch 96/200
71/71 [==============================] - 0s 379us/sample - loss: 188.8417
Epoch 97/200
71/71 [==============================] - 0s 365us/sample - loss: 190.4412
Epoch 98/200
71/71 [==============================] - 0s 365us/sample - loss: 191.5159
Epoch 99/200
71/71 [==============================] - 0s 337us/sample - loss: 189.7074
Epoch 100/200
71/71 [==============================] - 0s 323us/sample - loss: 187.4221
Epoch 101/200
71/71 [==============================] - 0s 365us/sample - loss: 185.1331
Epoch 102/200
71/71 [==============================] - 0s 323us/sample - loss: 183.5156
Epoch 103/200
71/71 [==============================] - 0s 366us/sample - loss: 185.1543
Epoch 104/200
71/71 [==============================] - 0s 323us/sample - loss: 181.2107
Epoch 105/200
71/71 [==============================] - 0s 337us/sample - loss: 183.1694
Epoch 106/200
71/71 [==============================] - 0s 323us/sample - loss: 196.2921
Epoch 107/200
71/71 [==============================] - 0s 323us/sample - loss: 194.4614
Epoch 108/200
71/71 [==============================] - 0s 334us/sample - loss: 180.9346
Epoch 109/200
71/71 [==============================] - 0s 365us/sample - loss: 195.0747
Epoch 110/200
71/71 [==============================] - 0s 323us/sample - loss: 191.8802
Epoch 111/200
71/71 [==============================] - 0s 309us/sample - loss: 180.4117
Epoch 112/200
71/71 [==============================] - 0s 337us/sample - loss: 189.2952
Epoch 113/200
71/71 [==============================] - 0s 351us/sample - loss: 188.1776
Epoch 114/200
71/71 [==============================] - 0s 337us/sample - loss: 180.4017
Epoch 115/200
71/71 [==============================] - 0s 323us/sample - loss: 177.8305
Epoch 116/200
71/71 [==============================] - 0s 335us/sample - loss: 176.9570
Epoch 117/200
71/71 [==============================] - 0s 337us/sample - loss: 177.1100
Epoch 118/200
71/71 [==============================] - 0s 365us/sample - loss: 174.0881
Epoch 119/200
71/71 [==============================] - 0s 351us/sample - loss: 174.4373
Epoch 120/200
71/71 [==============================] - 0s 331us/sample - loss: 174.2955
Epoch 121/200
71/71 [==============================] - 0s 323us/sample - loss: 175.3179
Epoch 122/200
71/71 [==============================] - 0s 337us/sample - loss: 184.3139
Epoch 123/200
71/71 [==============================] - 0s 323us/sample - loss: 172.8068
Epoch 124/200
71/71 [==============================] - 0s 351us/sample - loss: 172.2903
Epoch 125/200
71/71 [==============================] - 0s 337us/sample - loss: 170.9398
Epoch 126/200
71/71 [==============================] - 0s 365us/sample - loss: 169.0428
Epoch 127/200
71/71 [==============================] - 0s 309us/sample - loss: 168.9582
Epoch 128/200
71/71 [==============================] - 0s 323us/sample - loss: 168.0469
Epoch 129/200
71/71 [==============================] - 0s 323us/sample - loss: 166.6321
Epoch 130/200
71/71 [==============================] - 0s 365us/sample - loss: 166.2648
Epoch 131/200
71/71 [==============================] - 0s 337us/sample - loss: 166.2690
Epoch 132/200
71/71 [==============================] - 0s 340us/sample - loss: 165.6276
Epoch 133/200
71/71 [==============================] - 0s 351us/sample - loss: 166.5501
Epoch 134/200
71/71 [==============================] - 0s 351us/sample - loss: 169.6716
Epoch 135/200
71/71 [==============================] - 0s 365us/sample - loss: 165.2549
Epoch 136/200
71/71 [==============================] - 0s 351us/sample - loss: 163.7900
Epoch 137/200
71/71 [==============================] - 0s 337us/sample - loss: 162.6787
Epoch 138/200
71/71 [==============================] - 0s 337us/sample - loss: 160.7894
Epoch 139/200
71/71 [==============================] - 0s 323us/sample - loss: 160.5716
Epoch 140/200
71/71 [==============================] - 0s 351us/sample - loss: 160.0419
Epoch 141/200
71/71 [==============================] - 0s 365us/sample - loss: 158.9999
Epoch 142/200
71/71 [==============================] - 0s 323us/sample - loss: 158.1991
Epoch 143/200
71/71 [==============================] - 0s 323us/sample - loss: 156.1340
Epoch 144/200
71/71 [==============================] - 0s 323us/sample - loss: 162.0699
Epoch 145/200
71/71 [==============================] - 0s 323us/sample - loss: 158.9677
Epoch 146/200
71/71 [==============================] - 0s 336us/sample - loss: 165.5888
Epoch 147/200
71/71 [==============================] - 0s 323us/sample - loss: 159.0835
Epoch 148/200
71/71 [==============================] - 0s 351us/sample - loss: 200.7802
Epoch 149/200
71/71 [==============================] - 0s 365us/sample - loss: 168.8075
Epoch 150/200
71/71 [==============================] - 0s 337us/sample - loss: 173.3913
Epoch 151/200
71/71 [==============================] - 0s 365us/sample - loss: 174.2896
Epoch 152/200
71/71 [==============================] - 0s 328us/sample - loss: 163.7480
Epoch 153/200
71/71 [==============================] - 0s 323us/sample - loss: 167.4954
Epoch 154/200
71/71 [==============================] - 0s 365us/sample - loss: 160.4366
Epoch 155/200
71/71 [==============================] - 0s 365us/sample - loss: 156.2170
Epoch 156/200
71/71 [==============================] - 0s 351us/sample - loss: 156.7312
Epoch 157/200
71/71 [==============================] - 0s 351us/sample - loss: 153.3264
Epoch 158/200
71/71 [==============================] - 0s 337us/sample - loss: 151.8507
Epoch 159/200
71/71 [==============================] - 0s 365us/sample - loss: 147.7963
Epoch 160/200
71/71 [==============================] - 0s 323us/sample - loss: 150.4301
Epoch 161/200
71/71 [==============================] - 0s 351us/sample - loss: 148.9684
Epoch 162/200
71/71 [==============================] - 0s 323us/sample - loss: 145.4668
Epoch 163/200
71/71 [==============================] - 0s 337us/sample - loss: 143.9964
Epoch 164/200
71/71 [==============================] - 0s 331us/sample - loss: 141.3660
Epoch 165/200
71/71 [==============================] - 0s 379us/sample - loss: 138.4417
Epoch 166/200
71/71 [==============================] - 0s 351us/sample - loss: 144.8524
Epoch 167/200
71/71 [==============================] - 0s 337us/sample - loss: 141.0720
Epoch 168/200
71/71 [==============================] - 0s 323us/sample - loss: 144.8438
Epoch 169/200
71/71 [==============================] - 0s 337us/sample - loss: 134.8012
Epoch 170/200
71/71 [==============================] - 0s 337us/sample - loss: 136.6710
Epoch 171/200
71/71 [==============================] - 0s 351us/sample - loss: 133.2994
Epoch 172/200
71/71 [==============================] - 0s 309us/sample - loss: 133.0605
Epoch 173/200
71/71 [==============================] - 0s 351us/sample - loss: 135.3201
Epoch 174/200
71/71 [==============================] - 0s 365us/sample - loss: 130.4498
Epoch 175/200
71/71 [==============================] - 0s 407us/sample - loss: 129.9003
Epoch 176/200
71/71 [==============================] - 0s 323us/sample - loss: 126.9996
Epoch 177/200
71/71 [==============================] - 0s 379us/sample - loss: 125.1143
Epoch 178/200
71/71 [==============================] - 0s 379us/sample - loss: 121.1653
Epoch 179/200
71/71 [==============================] - 0s 366us/sample - loss: 125.0785
Epoch 180/200
71/71 [==============================] - 0s 337us/sample - loss: 119.2013
Epoch 181/200
71/71 [==============================] - 0s 379us/sample - loss: 130.0464
Epoch 182/200
71/71 [==============================] - 0s 351us/sample - loss: 115.6900
Epoch 183/200
71/71 [==============================] - 0s 351us/sample - loss: 114.6732
Epoch 184/200
71/71 [==============================] - 0s 337us/sample - loss: 116.7013
Epoch 185/200
71/71 [==============================] - 0s 407us/sample - loss: 112.9706
Epoch 186/200
71/71 [==============================] - 0s 365us/sample - loss: 113.7457
Epoch 187/200
71/71 [==============================] - 0s 379us/sample - loss: 117.9133
Epoch 188/200
71/71 [==============================] - 0s 380us/sample - loss: 119.6261
Epoch 189/200
71/71 [==============================] - 0s 379us/sample - loss: 113.7609
Epoch 190/200
71/71 [==============================] - 0s 323us/sample - loss: 107.2183
Epoch 191/200
71/71 [==============================] - 0s 347us/sample - loss: 108.2377
Epoch 192/200
71/71 [==============================] - 0s 407us/sample - loss: 105.1993
Epoch 193/200
71/71 [==============================] - 0s 351us/sample - loss: 103.7858
Epoch 194/200
71/71 [==============================] - 0s 403us/sample - loss: 110.5392
Epoch 195/200
71/71 [==============================] - 0s 349us/sample - loss: 107.6421
Epoch 196/200
71/71 [==============================] - 0s 365us/sample - loss: 103.9309
Epoch 197/200
71/71 [==============================] - 0s 365us/sample - loss: 103.2113
Epoch 198/200
71/71 [==============================] - 0s 368us/sample - loss: 100.2022
Epoch 199/200
71/71 [==============================] - 0s 365us/sample - loss: 121.3559
Epoch 200/200
71/71 [==============================] - 0s 379us/sample - loss: 101.8714
GUARUJÁ-IPORANGA-102
Train on 98 samples
Epoch 1/200
98/98 [==============================] - 2s 19ms/sample - loss: 582.9359
Epoch 2/200
98/98 [==============================] - 0s 336us/sample - loss: 550.1363
Epoch 3/200
98/98 [==============================] - 0s 351us/sample - loss: 525.7249
Epoch 4/200
98/98 [==============================] - 0s 336us/sample - loss: 513.2722
Epoch 5/200
98/98 [==============================] - 0s 356us/sample - loss: 499.7279
Epoch 6/200
98/98 [==============================] - 0s 315us/sample - loss: 488.5030
Epoch 7/200
98/98 [==============================] - 0s 312us/sample - loss: 479.9801
Epoch 8/200
98/98 [==============================] - 0s 336us/sample - loss: 472.7302
Epoch 9/200
98/98 [==============================] - 0s 356us/sample - loss: 460.6582
Epoch 10/200
98/98 [==============================] - 0s 336us/sample - loss: 447.4944
Epoch 11/200
98/98 [==============================] - 0s 336us/sample - loss: 447.9901
Epoch 12/200
98/98 [==============================] - 0s 336us/sample - loss: 443.4218
Epoch 13/200
98/98 [==============================] - 0s 372us/sample - loss: 432.6400
Epoch 14/200
98/98 [==============================] - 0s 326us/sample - loss: 422.2329
Epoch 15/200
98/98 [==============================] - 0s 336us/sample - loss: 417.0312
Epoch 16/200
98/98 [==============================] - 0s 305us/sample - loss: 407.0406
Epoch 17/200
98/98 [==============================] - 0s 325us/sample - loss: 395.6290
Epoch 18/200
98/98 [==============================] - 0s 315us/sample - loss: 391.3940
Epoch 19/200
98/98 [==============================] - 0s 366us/sample - loss: 374.8358
Epoch 20/200
98/98 [==============================] - 0s 366us/sample - loss: 366.3607
Epoch 21/200
98/98 [==============================] - 0s 325us/sample - loss: 363.2656
Epoch 22/200
98/98 [==============================] - 0s 336us/sample - loss: 362.2516
Epoch 23/200
98/98 [==============================] - 0s 315us/sample - loss: 357.8794
Epoch 24/200
98/98 [==============================] - 0s 305us/sample - loss: 354.6600
Epoch 25/200
98/98 [==============================] - 0s 305us/sample - loss: 352.8189
Epoch 26/200
98/98 [==============================] - 0s 326us/sample - loss: 361.6779
Epoch 27/200
98/98 [==============================] - 0s 326us/sample - loss: 339.8027
Epoch 28/200
98/98 [==============================] - 0s 326us/sample - loss: 367.6497
Epoch 29/200
98/98 [==============================] - 0s 346us/sample - loss: 376.9254
Epoch 30/200
98/98 [==============================] - 0s 305us/sample - loss: 360.4552
Epoch 31/200
98/98 [==============================] - 0s 336us/sample - loss: 358.1920
Epoch 32/200
98/98 [==============================] - 0s 366us/sample - loss: 373.7465
Epoch 33/200
98/98 [==============================] - 0s 346us/sample - loss: 366.3938
Epoch 34/200
98/98 [==============================] - 0s 315us/sample - loss: 352.9577
Epoch 35/200
98/98 [==============================] - 0s 315us/sample - loss: 344.6013
Epoch 36/200
98/98 [==============================] - 0s 346us/sample - loss: 343.0539
Epoch 37/200
98/98 [==============================] - 0s 326us/sample - loss: 378.5845
Epoch 38/200
98/98 [==============================] - 0s 346us/sample - loss: 393.7012
Epoch 39/200
98/98 [==============================] - 0s 407us/sample - loss: 369.6500
Epoch 40/200
98/98 [==============================] - 0s 356us/sample - loss: 350.7330
Epoch 41/200
98/98 [==============================] - 0s 320us/sample - loss: 349.4546
Epoch 42/200
98/98 [==============================] - 0s 315us/sample - loss: 343.8405
Epoch 43/200
98/98 [==============================] - 0s 336us/sample - loss: 336.8894
Epoch 44/200
98/98 [==============================] - 0s 356us/sample - loss: 329.3419
Epoch 45/200
98/98 [==============================] - 0s 356us/sample - loss: 327.8545
Epoch 46/200
98/98 [==============================] - 0s 338us/sample - loss: 340.8989
Epoch 47/200
98/98 [==============================] - 0s 336us/sample - loss: 328.5588
Epoch 48/200
98/98 [==============================] - 0s 352us/sample - loss: 332.6247
Epoch 49/200
98/98 [==============================] - 0s 346us/sample - loss: 347.0890
Epoch 50/200
98/98 [==============================] - 0s 346us/sample - loss: 352.6254
Epoch 51/200
98/98 [==============================] - 0s 341us/sample - loss: 346.9561
Epoch 52/200
98/98 [==============================] - 0s 356us/sample - loss: 336.8062
Epoch 53/200
98/98 [==============================] - 0s 326us/sample - loss: 327.7685
Epoch 54/200
98/98 [==============================] - 0s 315us/sample - loss: 327.9781
Epoch 55/200
98/98 [==============================] - 0s 346us/sample - loss: 326.7479
Epoch 56/200
98/98 [==============================] - 0s 326us/sample - loss: 321.6290
Epoch 57/200
98/98 [==============================] - 0s 315us/sample - loss: 341.5298
Epoch 58/200
98/98 [==============================] - 0s 336us/sample - loss: 333.6932
Epoch 59/200
98/98 [==============================] - 0s 315us/sample - loss: 319.7872
Epoch 60/200
98/98 [==============================] - 0s 332us/sample - loss: 322.2420
Epoch 61/200
98/98 [==============================] - 0s 325us/sample - loss: 329.5679
Epoch 62/200
98/98 [==============================] - 0s 336us/sample - loss: 343.1043
Epoch 63/200
98/98 [==============================] - 0s 336us/sample - loss: 328.3865
Epoch 64/200
98/98 [==============================] - 0s 369us/sample - loss: 332.1516
Epoch 65/200
98/98 [==============================] - 0s 316us/sample - loss: 354.2623
Epoch 66/200
98/98 [==============================] - 0s 346us/sample - loss: 356.3525
Epoch 67/200
98/98 [==============================] - 0s 356us/sample - loss: 350.3723
Epoch 68/200
98/98 [==============================] - 0s 397us/sample - loss: 337.7607
Epoch 69/200
98/98 [==============================] - 0s 305us/sample - loss: 330.5852
Epoch 70/200
98/98 [==============================] - 0s 356us/sample - loss: 322.5855
Epoch 71/200
98/98 [==============================] - 0s 305us/sample - loss: 321.6152
Epoch 72/200
98/98 [==============================] - 0s 315us/sample - loss: 317.9597
Epoch 73/200
98/98 [==============================] - 0s 336us/sample - loss: 312.6634
Epoch 74/200
98/98 [==============================] - 0s 356us/sample - loss: 311.1316
Epoch 75/200
98/98 [==============================] - 0s 376us/sample - loss: 310.7166
Epoch 76/200
98/98 [==============================] - 0s 336us/sample - loss: 311.0908
Epoch 77/200
98/98 [==============================] - 0s 326us/sample - loss: 310.8701
Epoch 78/200
98/98 [==============================] - 0s 356us/sample - loss: 307.0102
Epoch 79/200
98/98 [==============================] - 0s 336us/sample - loss: 310.9313
Epoch 80/200
98/98 [==============================] - 0s 323us/sample - loss: 309.9882
Epoch 81/200

98/98 [==============================] - 0s 326us/sample - loss: 304.1991
Epoch 82/200
98/98 [==============================] - 0s 346us/sample - loss: 301.7680
Epoch 83/200
98/98 [==============================] - 0s 346us/sample - loss: 305.6520
Epoch 84/200
98/98 [==============================] - 0s 315us/sample - loss: 308.7805
Epoch 85/200
98/98 [==============================] - 0s 326us/sample - loss: 307.8408
Epoch 86/200
98/98 [==============================] - 0s 325us/sample - loss: 305.6200
Epoch 87/200
98/98 [==============================] - 0s 326us/sample - loss: 303.5203
Epoch 88/200
98/98 [==============================] - 0s 351us/sample - loss: 305.9680
Epoch 89/200
98/98 [==============================] - 0s 315us/sample - loss: 304.5924
Epoch 90/200
98/98 [==============================] - 0s 326us/sample - loss: 301.4818
Epoch 91/200
98/98 [==============================] - 0s 346us/sample - loss: 299.2686
Epoch 92/200
98/98 [==============================] - 0s 316us/sample - loss: 299.6502
Epoch 93/200
98/98 [==============================] - 0s 305us/sample - loss: 297.4433
Epoch 94/200
98/98 [==============================] - 0s 315us/sample - loss: 299.8724
Epoch 95/200
98/98 [==============================] - 0s 305us/sample - loss: 300.2634
Epoch 96/200
98/98 [==============================] - 0s 321us/sample - loss: 295.3811
Epoch 97/200
98/98 [==============================] - 0s 336us/sample - loss: 292.0703
Epoch 98/200
98/98 [==============================] - 0s 382us/sample - loss: 291.4515
Epoch 99/200
98/98 [==============================] - 0s 295us/sample - loss: 293.5460
Epoch 100/200
98/98 [==============================] - 0s 341us/sample - loss: 295.6172
Epoch 101/200
98/98 [==============================] - 0s 316us/sample - loss: 296.7621
Epoch 102/200
98/98 [==============================] - 0s 341us/sample - loss: 291.9886
Epoch 103/200
98/98 [==============================] - 0s 336us/sample - loss: 291.8139
Epoch 104/200
98/98 [==============================] - 0s 346us/sample - loss: 288.6358
Epoch 105/200
98/98 [==============================] - 0s 325us/sample - loss: 288.4916
Epoch 106/200
98/98 [==============================] - 0s 346us/sample - loss: 310.2211
Epoch 107/200
98/98 [==============================] - 0s 325us/sample - loss: 319.8055
Epoch 108/200
98/98 [==============================] - 0s 356us/sample - loss: 315.1136
Epoch 109/200
98/98 [==============================] - 0s 326us/sample - loss: 302.9336
Epoch 110/200
98/98 [==============================] - 0s 336us/sample - loss: 292.0422
Epoch 111/200
98/98 [==============================] - 0s 326us/sample - loss: 292.3090
Epoch 112/200
98/98 [==============================] - 0s 337us/sample - loss: 292.3467
Epoch 113/200
98/98 [==============================] - 0s 305us/sample - loss: 294.1680
Epoch 114/200
98/98 [==============================] - 0s 305us/sample - loss: 294.0790
Epoch 115/200
98/98 [==============================] - 0s 346us/sample - loss: 284.9168
Epoch 116/200
98/98 [==============================] - 0s 346us/sample - loss: 281.1114
Epoch 117/200
98/98 [==============================] - 0s 368us/sample - loss: 276.9491
Epoch 118/200
98/98 [==============================] - 0s 326us/sample - loss: 277.6701
Epoch 119/200
98/98 [==============================] - 0s 315us/sample - loss: 274.2292
Epoch 120/200
98/98 [==============================] - 0s 348us/sample - loss: 272.8433
Epoch 121/200
98/98 [==============================] - 0s 366us/sample - loss: 275.0571
Epoch 122/200
98/98 [==============================] - 0s 366us/sample - loss: 270.8190
Epoch 123/200
98/98 [==============================] - 0s 321us/sample - loss: 271.9754
Epoch 124/200
98/98 [==============================] - 0s 315us/sample - loss: 262.8518
Epoch 125/200
98/98 [==============================] - 0s 326us/sample - loss: 260.5147
Epoch 126/200
98/98 [==============================] - 0s 315us/sample - loss: 261.0815
Epoch 127/200
98/98 [==============================] - 0s 376us/sample - loss: 259.2734
Epoch 128/200
98/98 [==============================] - 0s 356us/sample - loss: 263.7710
Epoch 129/200
98/98 [==============================] - 0s 326us/sample - loss: 265.4451
Epoch 130/200
98/98 [==============================] - 0s 336us/sample - loss: 290.5095
Epoch 131/200
98/98 [==============================] - 0s 341us/sample - loss: 393.0898
Epoch 132/200
98/98 [==============================] - 0s 326us/sample - loss: 324.7053
Epoch 133/200
98/98 [==============================] - 0s 381us/sample - loss: 354.6710
Epoch 134/200
98/98 [==============================] - 0s 326us/sample - loss: 294.7043
Epoch 135/200
98/98 [==============================] - 0s 336us/sample - loss: 295.8398
Epoch 136/200
98/98 [==============================] - 0s 336us/sample - loss: 298.6476
Epoch 137/200
98/98 [==============================] - 0s 336us/sample - loss: 298.0166
Epoch 138/200
98/98 [==============================] - 0s 325us/sample - loss: 289.0141
Epoch 139/200
98/98 [==============================] - 0s 332us/sample - loss: 294.8094
Epoch 140/200
98/98 [==============================] - 0s 316us/sample - loss: 289.7269
Epoch 141/200
98/98 [==============================] - 0s 325us/sample - loss: 283.0673
Epoch 142/200
98/98 [==============================] - 0s 315us/sample - loss: 273.0618
Epoch 143/200
98/98 [==============================] - 0s 315us/sample - loss: 265.7413
Epoch 144/200
98/98 [==============================] - 0s 326us/sample - loss: 290.6378
Epoch 145/200
98/98 [==============================] - 0s 356us/sample - loss: 296.9351
Epoch 146/200
98/98 [==============================] - 0s 336us/sample - loss: 287.5602
Epoch 147/200
98/98 [==============================] - 0s 346us/sample - loss: 283.9934
Epoch 148/200
98/98 [==============================] - 0s 336us/sample - loss: 274.3909
Epoch 149/200
98/98 [==============================] - 0s 346us/sample - loss: 271.9622
Epoch 150/200
98/98 [==============================] - 0s 336us/sample - loss: 263.0983
Epoch 151/200
98/98 [==============================] - 0s 326us/sample - loss: 259.9922
Epoch 152/200
98/98 [==============================] - 0s 295us/sample - loss: 257.7240
Epoch 153/200
98/98 [==============================] - 0s 295us/sample - loss: 251.5132
Epoch 154/200
98/98 [==============================] - 0s 336us/sample - loss: 250.4924
Epoch 155/200
98/98 [==============================] - 0s 295us/sample - loss: 249.5180
Epoch 156/200
98/98 [==============================] - 0s 315us/sample - loss: 248.8414
Epoch 157/200
98/98 [==============================] - 0s 338us/sample - loss: 247.4015
Epoch 158/200
98/98 [==============================] - 0s 336us/sample - loss: 245.5952
Epoch 159/200
98/98 [==============================] - 0s 321us/sample - loss: 253.7505
Epoch 160/200
98/98 [==============================] - 0s 326us/sample - loss: 266.8871
Epoch 161/200
98/98 [==============================] - 0s 315us/sample - loss: 263.8038
Epoch 162/200
98/98 [==============================] - 0s 328us/sample - loss: 262.1808
Epoch 163/200
98/98 [==============================] - 0s 326us/sample - loss: 273.7299
Epoch 164/200
98/98 [==============================] - 0s 346us/sample - loss: 276.6703
Epoch 165/200
98/98 [==============================] - 0s 334us/sample - loss: 270.9290
Epoch 166/200
98/98 [==============================] - 0s 336us/sample - loss: 262.9541
Epoch 167/200
98/98 [==============================] - 0s 315us/sample - loss: 263.1218
Epoch 168/200
98/98 [==============================] - 0s 326us/sample - loss: 282.8471
Epoch 169/200
98/98 [==============================] - 0s 336us/sample - loss: 304.3656
Epoch 170/200
98/98 [==============================] - 0s 336us/sample - loss: 291.5703
Epoch 171/200
98/98 [==============================] - 0s 320us/sample - loss: 289.8922
Epoch 172/200
98/98 [==============================] - 0s 336us/sample - loss: 278.1320
Epoch 173/200
98/98 [==============================] - 0s 356us/sample - loss: 278.1439
Epoch 174/200
98/98 [==============================] - 0s 379us/sample - loss: 270.6548
Epoch 175/200
98/98 [==============================] - 0s 359us/sample - loss: 267.4720
Epoch 176/200
98/98 [==============================] - 0s 326us/sample - loss: 260.6770
Epoch 177/200
98/98 [==============================] - 0s 336us/sample - loss: 254.9995
Epoch 178/200
98/98 [==============================] - 0s 336us/sample - loss: 288.0497
Epoch 179/200
98/98 [==============================] - 0s 305us/sample - loss: 279.6471
Epoch 180/200
98/98 [==============================] - 0s 326us/sample - loss: 279.7191
Epoch 181/200
98/98 [==============================] - 0s 336us/sample - loss: 262.7368
Epoch 182/200
98/98 [==============================] - 0s 315us/sample - loss: 268.8750
Epoch 183/200
98/98 [==============================] - 0s 325us/sample - loss: 268.2937
Epoch 184/200
98/98 [==============================] - 0s 325us/sample - loss: 269.9343
Epoch 185/200
98/98 [==============================] - 0s 326us/sample - loss: 279.2086
Epoch 186/200
98/98 [==============================] - 0s 336us/sample - loss: 277.8523
Epoch 187/200
98/98 [==============================] - 0s 366us/sample - loss: 260.4317
Epoch 188/200
98/98 [==============================] - 0s 336us/sample - loss: 251.2920
Epoch 189/200
98/98 [==============================] - 0s 336us/sample - loss: 242.1427
Epoch 190/200
98/98 [==============================] - 0s 336us/sample - loss: 240.6730
Epoch 191/200
98/98 [==============================] - 0s 305us/sample - loss: 237.0108
Epoch 192/200
98/98 [==============================] - 0s 305us/sample - loss: 233.8432
Epoch 193/200
98/98 [==============================] - 0s 335us/sample - loss: 233.2855
Epoch 194/200
98/98 [==============================] - 0s 305us/sample - loss: 232.1409
Epoch 195/200
98/98 [==============================] - 0s 321us/sample - loss: 234.0564
Epoch 196/200
98/98 [==============================] - 0s 315us/sample - loss: 238.9709
Epoch 197/200
98/98 [==============================] - 0s 356us/sample - loss: 231.0092
Epoch 198/200
98/98 [==============================] - 0s 334us/sample - loss: 236.7220
Epoch 199/200
98/98 [==============================] - 0s 346us/sample - loss: 234.6980
Epoch 200/200
98/98 [==============================] - 0s 315us/sample - loss: 231.7293
IGUAPE-JURÉIA-232
Train on 90 samples
Epoch 1/200
90/90 [==============================] - 2s 20ms/sample - loss: 4707.0500
Epoch 2/200
90/90 [==============================] - 0s 266us/sample - loss: 4622.9253
Epoch 3/200
90/90 [==============================] - 0s 255us/sample - loss: 4525.4790
Epoch 4/200
90/90 [==============================] - 0s 266us/sample - loss: 4480.9179
Epoch 5/200
90/90 [==============================] - 0s 272us/sample - loss: 4435.3536
Epoch 6/200
90/90 [==============================] - 0s 299us/sample - loss: 4392.8381
Epoch 7/200
90/90 [==============================] - 0s 277us/sample - loss: 4355.5459
Epoch 8/200
90/90 [==============================] - 0s 266us/sample - loss: 4294.5353
Epoch 9/200
90/90 [==============================] - 0s 277us/sample - loss: 4251.3682
Epoch 10/200
90/90 [==============================] - 0s 283us/sample - loss: 4225.1438
Epoch 11/200
90/90 [==============================] - 0s 288us/sample - loss: 4143.3811
Epoch 12/200
90/90 [==============================] - 0s 255us/sample - loss: 4111.0831
Epoch 13/200
90/90 [==============================] - 0s 277us/sample - loss: 4044.0694
Epoch 14/200
90/90 [==============================] - 0s 328us/sample - loss: 3979.4398
Epoch 15/200
90/90 [==============================] - 0s 266us/sample - loss: 3924.2334
Epoch 16/200
90/90 [==============================] - 0s 288us/sample - loss: 3839.1201
Epoch 17/200
90/90 [==============================] - 0s 255us/sample - loss: 3746.2307
Epoch 18/200
90/90 [==============================] - 0s 251us/sample - loss: 3685.6991
Epoch 19/200
90/90 [==============================] - 0s 277us/sample - loss: 3704.9769
Epoch 20/200
90/90 [==============================] - 0s 277us/sample - loss: 3573.4362
Epoch 21/200
90/90 [==============================] - 0s 400us/sample - loss: 3554.4754
Epoch 22/200
90/90 [==============================] - 0s 321us/sample - loss: 3479.3894
Epoch 23/200
90/90 [==============================] - 0s 288us/sample - loss: 3370.1059
Epoch 24/200
90/90 [==============================] - 0s 255us/sample - loss: 3320.7399
Epoch 25/200
90/90 [==============================] - 0s 310us/sample - loss: 3334.8102
Epoch 26/200
90/90 [==============================] - 0s 344us/sample - loss: 3265.4785
Epoch 27/200
90/90 [==============================] - 0s 299us/sample - loss: 3292.0539
Epoch 28/200
90/90 [==============================] - 0s 288us/sample - loss: 3179.1004
Epoch 29/200
90/90 [==============================] - 0s 299us/sample - loss: 3343.2412
Epoch 30/200
90/90 [==============================] - 0s 288us/sample - loss: 3188.0992
Epoch 31/200
90/90 [==============================] - 0s 266us/sample - loss: 3426.0708
Epoch 32/200
90/90 [==============================] - 0s 288us/sample - loss: 3145.3129
Epoch 33/200
90/90 [==============================] - 0s 299us/sample - loss: 3195.2742
Epoch 34/200
90/90 [==============================] - 0s 310us/sample - loss: 3150.9327
Epoch 35/200
90/90 [==============================] - 0s 288us/sample - loss: 3087.5046
Epoch 36/200
90/90 [==============================] - 0s 288us/sample - loss: 2996.2893
Epoch 37/200
90/90 [==============================] - 0s 266us/sample - loss: 2941.1309
Epoch 38/200
90/90 [==============================] - 0s 288us/sample - loss: 2870.0756
Epoch 39/200
90/90 [==============================] - 0s 288us/sample - loss: 2832.2600
Epoch 40/200
90/90 [==============================] - 0s 299us/sample - loss: 2781.2701
Epoch 41/200
90/90 [==============================] - 0s 277us/sample - loss: 2755.3369
Epoch 42/200
90/90 [==============================] - 0s 344us/sample - loss: 2709.4653
Epoch 43/200
90/90 [==============================] - 0s 288us/sample - loss: 2626.3343
Epoch 44/200
90/90 [==============================] - 0s 310us/sample - loss: 2553.6592
Epoch 45/200
90/90 [==============================] - 0s 299us/sample - loss: 2619.2494
Epoch 46/200
90/90 [==============================] - 0s 288us/sample - loss: 2698.6853
Epoch 47/200
90/90 [==============================] - 0s 310us/sample - loss: 2576.6986
Epoch 48/200
90/90 [==============================] - 0s 310us/sample - loss: 2412.7094
Epoch 49/200
90/90 [==============================] - 0s 321us/sample - loss: 2316.9605
Epoch 50/200
90/90 [==============================] - 0s 332us/sample - loss: 2300.6971
Epoch 51/200
90/90 [==============================] - 0s 332us/sample - loss: 2219.6228
Epoch 52/200
90/90 [==============================] - 0s 321us/sample - loss: 2149.7439
Epoch 53/200
90/90 [==============================] - 0s 277us/sample - loss: 2039.2429
Epoch 54/200
90/90 [==============================] - 0s 308us/sample - loss: 1968.1625
Epoch 55/200
90/90 [==============================] - 0s 277us/sample - loss: 1929.9835
Epoch 56/200
90/90 [==============================] - 0s 288us/sample - loss: 1874.5466
Epoch 57/200
90/90 [==============================] - 0s 288us/sample - loss: 1801.7949
Epoch 58/200
90/90 [==============================] - 0s 255us/sample - loss: 2197.9619
Epoch 59/200
90/90 [==============================] - 0s 266us/sample - loss: 1938.4743
Epoch 60/200
90/90 [==============================] - 0s 266us/sample - loss: 1895.0276
Epoch 61/200
90/90 [==============================] - 0s 282us/sample - loss: 1798.6513
Epoch 62/200
90/90 [==============================] - 0s 269us/sample - loss: 1727.7554
Epoch 63/200
90/90 [==============================] - 0s 277us/sample - loss: 1886.6316
Epoch 64/200
90/90 [==============================] - 0s 299us/sample - loss: 2178.6901
Epoch 65/200
90/90 [==============================] - 0s 263us/sample - loss: 2019.3366
Epoch 66/200
90/90 [==============================] - 0s 266us/sample - loss: 1890.2613

Epoch 67/200
90/90 [==============================] - 0s 288us/sample - loss: 1943.1505
Epoch 68/200
90/90 [==============================] - 0s 255us/sample - loss: 1784.9088
Epoch 69/200
90/90 [==============================] - 0s 266us/sample - loss: 1694.9667
Epoch 70/200
90/90 [==============================] - 0s 283us/sample - loss: 1681.9149
Epoch 71/200
90/90 [==============================] - 0s 255us/sample - loss: 1608.5652
Epoch 72/200
90/90 [==============================] - 0s 277us/sample - loss: 1612.3073
Epoch 73/200
90/90 [==============================] - 0s 305us/sample - loss: 1526.7739
Epoch 74/200
90/90 [==============================] - 0s 277us/sample - loss: 1518.5228
Epoch 75/200
90/90 [==============================] - 0s 255us/sample - loss: 1479.2315
Epoch 76/200
90/90 [==============================] - 0s 255us/sample - loss: 1456.3653
Epoch 77/200
90/90 [==============================] - 0s 254us/sample - loss: 1420.1278
Epoch 78/200
90/90 [==============================] - 0s 299us/sample - loss: 1457.6531
Epoch 79/200
90/90 [==============================] - 0s 277us/sample - loss: 1395.0737
Epoch 80/200
90/90 [==============================] - 0s 277us/sample - loss: 1419.9793
Epoch 81/200
90/90 [==============================] - 0s 277us/sample - loss: 1388.7894
Epoch 82/200
90/90 [==============================] - 0s 255us/sample - loss: 1346.4263
Epoch 83/200
90/90 [==============================] - 0s 277us/sample - loss: 1333.0088
Epoch 84/200
90/90 [==============================] - 0s 266us/sample - loss: 1306.2351
Epoch 85/200
90/90 [==============================] - 0s 244us/sample - loss: 1324.0707
Epoch 86/200
90/90 [==============================] - 0s 266us/sample - loss: 1267.8847
Epoch 87/200
90/90 [==============================] - 0s 288us/sample - loss: 1305.7385
Epoch 88/200
90/90 [==============================] - 0s 266us/sample - loss: 1318.7294
Epoch 89/200
90/90 [==============================] - 0s 266us/sample - loss: 1259.6327
Epoch 90/200
90/90 [==============================] - 0s 255us/sample - loss: 1251.7462
Epoch 91/200
90/90 [==============================] - 0s 277us/sample - loss: 1206.2385
Epoch 92/200
90/90 [==============================] - 0s 277us/sample - loss: 1211.0478
Epoch 93/200
90/90 [==============================] - 0s 266us/sample - loss: 1171.5217
Epoch 94/200
90/90 [==============================] - 0s 277us/sample - loss: 1144.8404
Epoch 95/200
90/90 [==============================] - 0s 310us/sample - loss: 1202.7848
Epoch 96/200
90/90 [==============================] - 0s 299us/sample - loss: 1156.1840
Epoch 97/200
90/90 [==============================] - 0s 266us/sample - loss: 1236.7651
Epoch 98/200
90/90 [==============================] - 0s 266us/sample - loss: 1103.3310
Epoch 99/200
90/90 [==============================] - 0s 288us/sample - loss: 1141.7132
Epoch 100/200
90/90 [==============================] - 0s 277us/sample - loss: 1101.9676
Epoch 101/200
90/90 [==============================] - 0s 255us/sample - loss: 1277.2604
Epoch 102/200
90/90 [==============================] - 0s 288us/sample - loss: 1198.8062
Epoch 103/200
90/90 [==============================] - 0s 277us/sample - loss: 1137.9198
Epoch 104/200
90/90 [==============================] - 0s 277us/sample - loss: 1096.8870
Epoch 105/200
90/90 [==============================] - 0s 266us/sample - loss: 1183.8945
Epoch 106/200
90/90 [==============================] - 0s 266us/sample - loss: 1123.3740
Epoch 107/200
90/90 [==============================] - 0s 277us/sample - loss: 1056.9948
Epoch 108/200
90/90 [==============================] - 0s 266us/sample - loss: 1061.1682
Epoch 109/200
90/90 [==============================] - 0s 277us/sample - loss: 1025.9824
Epoch 110/200
90/90 [==============================] - 0s 277us/sample - loss: 997.6240
Epoch 111/200
90/90 [==============================] - 0s 266us/sample - loss: 1110.5094
Epoch 112/200
90/90 [==============================] - 0s 310us/sample - loss: 973.4508
Epoch 113/200
90/90 [==============================] - 0s 255us/sample - loss: 1012.2750
Epoch 114/200
90/90 [==============================] - 0s 266us/sample - loss: 1032.0412
Epoch 115/200
90/90 [==============================] - 0s 255us/sample - loss: 947.9922
Epoch 116/200
90/90 [==============================] - 0s 266us/sample - loss: 961.2287
Epoch 117/200
90/90 [==============================] - 0s 261us/sample - loss: 879.1084
Epoch 118/200
90/90 [==============================] - 0s 266us/sample - loss: 964.8133
Epoch 119/200
90/90 [==============================] - 0s 321us/sample - loss: 972.0457
Epoch 120/200
90/90 [==============================] - 0s 277us/sample - loss: 883.6297
Epoch 121/200
90/90 [==============================] - 0s 277us/sample - loss: 919.6837
Epoch 122/200
90/90 [==============================] - 0s 266us/sample - loss: 1055.0454
Epoch 123/200
90/90 [==============================] - 0s 277us/sample - loss: 916.9858
Epoch 124/200
90/90 [==============================] - 0s 255us/sample - loss: 1011.5888
Epoch 125/200
90/90 [==============================] - 0s 250us/sample - loss: 857.2342
Epoch 126/200
90/90 [==============================] - 0s 266us/sample - loss: 932.9034
Epoch 127/200
90/90 [==============================] - 0s 299us/sample - loss: 850.5414
Epoch 128/200
90/90 [==============================] - 0s 266us/sample - loss: 839.9225
Epoch 129/200
90/90 [==============================] - 0s 277us/sample - loss: 854.4618
Epoch 130/200
90/90 [==============================] - 0s 255us/sample - loss: 799.2674
Epoch 131/200
90/90 [==============================] - 0s 288us/sample - loss: 852.9561
Epoch 132/200
90/90 [==============================] - 0s 277us/sample - loss: 818.3107
Epoch 133/200
90/90 [==============================] - 0s 266us/sample - loss: 793.3089
Epoch 134/200
90/90 [==============================] - 0s 277us/sample - loss: 780.3003
Epoch 135/200
90/90 [==============================] - 0s 321us/sample - loss: 768.7971
Epoch 136/200
90/90 [==============================] - 0s 289us/sample - loss: 740.9773
Epoch 137/200
90/90 [==============================] - 0s 255us/sample - loss: 740.9946
Epoch 138/200
90/90 [==============================] - 0s 266us/sample - loss: 728.8093
Epoch 139/200
90/90 [==============================] - 0s 266us/sample - loss: 726.8016
Epoch 140/200
90/90 [==============================] - 0s 266us/sample - loss: 719.6289
Epoch 141/200
90/90 [==============================] - 0s 255us/sample - loss: 712.5584
Epoch 142/200
90/90 [==============================] - 0s 277us/sample - loss: 699.0454
Epoch 143/200
90/90 [==============================] - 0s 277us/sample - loss: 703.9403
Epoch 144/200
90/90 [==============================] - 0s 288us/sample - loss: 689.2763
Epoch 145/200
90/90 [==============================] - 0s 255us/sample - loss: 684.6957
Epoch 146/200
90/90 [==============================] - 0s 288us/sample - loss: 690.7107
Epoch 147/200
90/90 [==============================] - 0s 255us/sample - loss: 676.2362
Epoch 148/200
90/90 [==============================] - 0s 274us/sample - loss: 674.7633
Epoch 149/200
90/90 [==============================] - 0s 277us/sample - loss: 688.6208
Epoch 150/200
90/90 [==============================] - 0s 321us/sample - loss: 685.1174
Epoch 151/200
90/90 [==============================] - 0s 255us/sample - loss: 719.5016
Epoch 152/200
90/90 [==============================] - 0s 244us/sample - loss: 709.6900
Epoch 153/200
90/90 [==============================] - 0s 277us/sample - loss: 708.1739
Epoch 154/200
90/90 [==============================] - 0s 277us/sample - loss: 684.6594
Epoch 155/200
90/90 [==============================] - 0s 266us/sample - loss: 733.7248
Epoch 156/200
90/90 [==============================] - 0s 277us/sample - loss: 673.0693
Epoch 157/200
90/90 [==============================] - 0s 255us/sample - loss: 727.2537
Epoch 158/200
90/90 [==============================] - 0s 299us/sample - loss: 715.0137
Epoch 159/200
90/90 [==============================] - 0s 255us/sample - loss: 690.3790

Epoch 160/200
90/90 [==============================] - 0s 255us/sample - loss: 679.7792
Epoch 161/200
90/90 [==============================] - 0s 255us/sample - loss: 716.5942
Epoch 162/200
90/90 [==============================] - 0s 299us/sample - loss: 689.2331
Epoch 163/200
90/90 [==============================] - 0s 266us/sample - loss: 734.9687
Epoch 164/200
90/90 [==============================] - 0s 266us/sample - loss: 744.0153
Epoch 165/200
90/90 [==============================] - 0s 255us/sample - loss: 784.5084
Epoch 166/200
90/90 [==============================] - 0s 288us/sample - loss: 733.7467
Epoch 167/200
90/90 [==============================] - 0s 277us/sample - loss: 762.1436
Epoch 168/200
90/90 [==============================] - 0s 255us/sample - loss: 692.1853
Epoch 169/200
90/90 [==============================] - 0s 255us/sample - loss: 695.3288
Epoch 170/200
90/90 [==============================] - 0s 244us/sample - loss: 696.4950
Epoch 171/200
90/90 [==============================] - 0s 266us/sample - loss: 1329.2751
Epoch 172/200
90/90 [==============================] - 0s 277us/sample - loss: 863.8389
Epoch 173/200
90/90 [==============================] - 0s 266us/sample - loss: 1365.0966
Epoch 174/200
90/90 [==============================] - 0s 321us/sample - loss: 1422.4622
Epoch 175/200
90/90 [==============================] - 0s 288us/sample - loss: 1292.8841
Epoch 176/200
90/90 [==============================] - 0s 266us/sample - loss: 1253.3760
Epoch 177/200
90/90 [==============================] - 0s 255us/sample - loss: 1309.0665
Epoch 178/200
90/90 [==============================] - 0s 288us/sample - loss: 1113.1530
Epoch 179/200
90/90 [==============================] - 0s 255us/sample - loss: 1274.4902
Epoch 180/200
90/90 [==============================] - 0s 266us/sample - loss: 1135.1544
Epoch 181/200
90/90 [==============================] - 0s 244us/sample - loss: 1076.6753
Epoch 182/200
90/90 [==============================] - 0s 277us/sample - loss: 1098.8482
Epoch 183/200
90/90 [==============================] - 0s 288us/sample - loss: 929.9005
Epoch 184/200
90/90 [==============================] - 0s 284us/sample - loss: 939.3800
Epoch 185/200
90/90 [==============================] - 0s 266us/sample - loss: 903.3389
Epoch 186/200
90/90 [==============================] - 0s 265us/sample - loss: 865.9477
Epoch 187/200
90/90 [==============================] - 0s 277us/sample - loss: 805.0470
Epoch 188/200
90/90 [==============================] - 0s 299us/sample - loss: 765.4917
Epoch 189/200
90/90 [==============================] - 0s 277us/sample - loss: 751.1017
Epoch 190/200
90/90 [==============================] - 0s 310us/sample - loss: 675.3835
Epoch 191/200
90/90 [==============================] - 0s 255us/sample - loss: 719.9039
Epoch 192/200
90/90 [==============================] - 0s 244us/sample - loss: 645.4067
Epoch 193/200
90/90 [==============================] - 0s 277us/sample - loss: 648.4240
Epoch 194/200
90/90 [==============================] - 0s 310us/sample - loss: 632.1496
Epoch 195/200
90/90 [==============================] - 0s 266us/sample - loss: 637.1180
Epoch 196/200
90/90 [==============================] - 0s 250us/sample - loss: 618.9682
Epoch 197/200
90/90 [==============================] - 0s 277us/sample - loss: 640.0275
Epoch 198/200
90/90 [==============================] - 0s 266us/sample - loss: 623.8256
Epoch 199/200
90/90 [==============================] - 0s 299us/sample - loss: 654.0191
Epoch 200/200
90/90 [==============================] - 0s 288us/sample - loss: 634.6484
ILHA COMPRIDA-BALNEÁRIO ADRIANA-635
Train on 98 samples
Epoch 1/200
98/98 [==============================] - 2s 17ms/sample - loss: 6219.0953
Epoch 2/200
98/98 [==============================] - 0s 366us/sample - loss: 6111.5567
Epoch 3/200
98/98 [==============================] - 0s 336us/sample - loss: 6037.4115
Epoch 4/200
98/98 [==============================] - 0s 326us/sample - loss: 5916.2428
Epoch 5/200
98/98 [==============================] - 0s 331us/sample - loss: 5858.7468
Epoch 6/200
98/98 [==============================] - 0s 336us/sample - loss: 5770.7623
Epoch 7/200
98/98 [==============================] - 0s 326us/sample - loss: 5727.4629
Epoch 8/200
98/98 [==============================] - 0s 336us/sample - loss: 5701.7768
Epoch 9/200
98/98 [==============================] - 0s 333us/sample - loss: 5681.5301
Epoch 10/200
98/98 [==============================] - 0s 326us/sample - loss: 5615.5722
Epoch 11/200
98/98 [==============================] - 0s 346us/sample - loss: 5488.1971
Epoch 12/200
98/98 [==============================] - 0s 315us/sample - loss: 5375.8701
Epoch 13/200
98/98 [==============================] - 0s 315us/sample - loss: 5248.5565
Epoch 14/200
98/98 [==============================] - 0s 427us/sample - loss: 5181.5503
Epoch 15/200
98/98 [==============================] - 0s 336us/sample - loss: 5123.9664
Epoch 16/200
98/98 [==============================] - 0s 315us/sample - loss: 4986.4455
Epoch 17/200
98/98 [==============================] - 0s 326us/sample - loss: 4806.2236
Epoch 18/200
98/98 [==============================] - 0s 305us/sample - loss: 4926.4419
Epoch 19/200
98/98 [==============================] - 0s 325us/sample - loss: 4821.8376
Epoch 20/200
98/98 [==============================] - 0s 356us/sample - loss: 4701.6894
Epoch 21/200
98/98 [==============================] - 0s 336us/sample - loss: 4676.4617
Epoch 22/200
98/98 [==============================] - 0s 341us/sample - loss: 4828.4773
Epoch 23/200
98/98 [==============================] - 0s 346us/sample - loss: 4809.0650
Epoch 24/200
98/98 [==============================] - 0s 326us/sample - loss: 4847.4882
Epoch 25/200
98/98 [==============================] - 0s 371us/sample - loss: 4702.9602
Epoch 26/200
98/98 [==============================] - 0s 356us/sample - loss: 4614.7875
Epoch 27/200
98/98 [==============================] - 0s 336us/sample - loss: 4562.1959
Epoch 28/200
98/98 [==============================] - 0s 366us/sample - loss: 4541.5956
Epoch 29/200
98/98 [==============================] - 0s 326us/sample - loss: 4418.1317
Epoch 30/200
98/98 [==============================] - 0s 336us/sample - loss: 4386.2941
Epoch 31/200
98/98 [==============================] - 0s 317us/sample - loss: 4396.7413
Epoch 32/200
98/98 [==============================] - 0s 343us/sample - loss: 4432.0065
Epoch 33/200
98/98 [==============================] - 0s 326us/sample - loss: 4469.6836
Epoch 34/200
98/98 [==============================] - 0s 366us/sample - loss: 4459.2420
Epoch 35/200
98/98 [==============================] - 0s 346us/sample - loss: 4370.5926
Epoch 36/200
98/98 [==============================] - 0s 326us/sample - loss: 4345.2221
Epoch 37/200
98/98 [==============================] - 0s 336us/sample - loss: 4309.4902
Epoch 38/200
98/98 [==============================] - 0s 326us/sample - loss: 4228.2346
Epoch 39/200
98/98 [==============================] - 0s 324us/sample - loss: 4109.0003
Epoch 40/200
98/98 [==============================] - 0s 325us/sample - loss: 4419.8066
Epoch 41/200
98/98 [==============================] - 0s 336us/sample - loss: 4565.4653
Epoch 42/200
98/98 [==============================] - 0s 372us/sample - loss: 4734.3281
Epoch 43/200
98/98 [==============================] - 0s 356us/sample - loss: 4576.8016
Epoch 44/200
98/98 [==============================] - 0s 336us/sample - loss: 4416.3109
Epoch 45/200
98/98 [==============================] - 0s 321us/sample - loss: 4427.1866
Epoch 46/200
98/98 [==============================] - 0s 305us/sample - loss: 4338.9035
Epoch 47/200
98/98 [==============================] - 0s 336us/sample - loss: 4339.8530
Epoch 48/200
98/98 [==============================] - 0s 336us/sample - loss: 4480.7291
Epoch 49/200
98/98 [==============================] - 0s 325us/sample - loss: 4277.2172
Epoch 50/200
98/98 [==============================] - 0s 320us/sample - loss: 4496.3070
Epoch 51/200
98/98 [==============================] - 0s 326us/sample - loss: 4527.0014
Epoch 52/200
98/98 [==============================] - 0s 336us/sample - loss: 5013.5688
Epoch 53/200
98/98 [==============================] - 0s 336us/sample - loss: 4279.7607
Epoch 54/200
98/98 [==============================] - 0s 356us/sample - loss: 4325.1833
Epoch 55/200
98/98 [==============================] - 0s 325us/sample - loss: 4540.2470
Epoch 56/200
98/98 [==============================] - 0s 342us/sample - loss: 4564.0252
Epoch 57/200
98/98 [==============================] - 0s 342us/sample - loss: 4446.5059
Epoch 58/200
98/98 [==============================] - 0s 305us/sample - loss: 4274.0838
Epoch 59/200
98/98 [==============================] - 0s 336us/sample - loss: 4269.7653
Epoch 60/200
98/98 [==============================] - 0s 341us/sample - loss: 4258.0705
Epoch 61/200
98/98 [==============================] - 0s 336us/sample - loss: 4134.3290
Epoch 62/200
98/98 [==============================] - 0s 326us/sample - loss: 4059.0458
Epoch 63/200
98/98 [==============================] - 0s 311us/sample - loss: 3917.8100
Epoch 64/200
98/98 [==============================] - 0s 305us/sample - loss: 3866.9204
Epoch 65/200
98/98 [==============================] - 0s 305us/sample - loss: 3823.0001
Epoch 66/200
98/98 [==============================] - 0s 361us/sample - loss: 4046.9768
Epoch 67/200
98/98 [==============================] - 0s 326us/sample - loss: 3677.1541
Epoch 68/200
98/98 [==============================] - 0s 326us/sample - loss: 3618.9213
Epoch 69/200
98/98 [==============================] - 0s 305us/sample - loss: 3656.7964
Epoch 70/200
98/98 [==============================] - 0s 326us/sample - loss: 3670.7999
Epoch 71/200
98/98 [==============================] - 0s 315us/sample - loss: 3607.5665
Epoch 72/200
98/98 [==============================] - 0s 315us/sample - loss: 4175.5132
Epoch 73/200
98/98 [==============================] - 0s 367us/sample - loss: 4441.3167
Epoch 74/200
98/98 [==============================] - 0s 326us/sample - loss: 4567.2799
Epoch 75/200
98/98 [==============================] - 0s 315us/sample - loss: 4439.6643
Epoch 76/200
98/98 [==============================] - 0s 336us/sample - loss: 4273.4813
Epoch 77/200
98/98 [==============================] - 0s 305us/sample - loss: 3642.1260
Epoch 78/200
98/98 [==============================] - 0s 356us/sample - loss: 3799.7916
Epoch 79/200
98/98 [==============================] - 0s 326us/sample - loss: 3527.5341
Epoch 80/200
98/98 [==============================] - 0s 315us/sample - loss: 3344.3385
Epoch 81/200
98/98 [==============================] - 0s 336us/sample - loss: 3235.0220
Epoch 82/200
98/98 [==============================] - 0s 336us/sample - loss: 3084.3804
Epoch 83/200
98/98 [==============================] - 0s 356us/sample - loss: 3385.7602
Epoch 84/200
98/98 [==============================] - 0s 351us/sample - loss: 3433.8135
Epoch 85/200
98/98 [==============================] - 0s 377us/sample - loss: 3005.5326
Epoch 86/200
98/98 [==============================] - 0s 356us/sample - loss: 3728.7873
Epoch 87/200
98/98 [==============================] - 0s 326us/sample - loss: 3511.1429
Epoch 88/200
98/98 [==============================] - 0s 336us/sample - loss: 3173.8899
Epoch 89/200
98/98 [==============================] - 0s 305us/sample - loss: 3459.4765
Epoch 90/200
98/98 [==============================] - 0s 356us/sample - loss: 4209.4205
Epoch 91/200
98/98 [==============================] - 0s 346us/sample - loss: 4722.9961
Epoch 92/200
98/98 [==============================] - 0s 336us/sample - loss: 4797.4868
Epoch 93/200
98/98 [==============================] - 0s 315us/sample - loss: 5279.4394
Epoch 94/200
98/98 [==============================] - 0s 336us/sample - loss: 4964.0323
Epoch 95/200
98/98 [==============================] - 0s 315us/sample - loss: 4748.0905
Epoch 96/200
98/98 [==============================] - 0s 326us/sample - loss: 4674.4159
Epoch 97/200
98/98 [==============================] - 0s 326us/sample - loss: 4636.0709
Epoch 98/200
98/98 [==============================] - 0s 336us/sample - loss: 4599.0573
Epoch 99/200
98/98 [==============================] - 0s 346us/sample - loss: 4602.6847
Epoch 100/200
98/98 [==============================] - 0s 326us/sample - loss: 4495.1464
Epoch 101/200
98/98 [==============================] - 0s 326us/sample - loss: 4403.6072
Epoch 102/200
98/98 [==============================] - 0s 336us/sample - loss: 4333.2527
Epoch 103/200
98/98 [==============================] - 0s 397us/sample - loss: 4294.5314
Epoch 104/200
98/98 [==============================] - 0s 336us/sample - loss: 4261.7912
Epoch 105/200
98/98 [==============================] - 0s 315us/sample - loss: 4229.0683
Epoch 106/200
98/98 [==============================] - 0s 326us/sample - loss: 4175.9249
Epoch 107/200
98/98 [==============================] - 0s 326us/sample - loss: 4140.2670
Epoch 108/200
98/98 [==============================] - 0s 351us/sample - loss: 4203.0065
Epoch 109/200
98/98 [==============================] - 0s 346us/sample - loss: 4196.4748
Epoch 110/200
98/98 [==============================] - 0s 325us/sample - loss: 4055.8382
Epoch 111/200
98/98 [==============================] - 0s 331us/sample - loss: 4106.6177
Epoch 112/200
98/98 [==============================] - 0s 326us/sample - loss: 4033.5702
Epoch 113/200
98/98 [==============================] - 0s 326us/sample - loss: 3959.7381
Epoch 114/200
98/98 [==============================] - 0s 348us/sample - loss: 3837.8475
Epoch 115/200
98/98 [==============================] - 0s 346us/sample - loss: 3756.1531
Epoch 116/200
98/98 [==============================] - 0s 326us/sample - loss: 3710.8119
Epoch 117/200
98/98 [==============================] - 0s 343us/sample - loss: 3597.9743
Epoch 118/200
98/98 [==============================] - 0s 326us/sample - loss: 3675.5484
Epoch 119/200
98/98 [==============================] - 0s 336us/sample - loss: 3719.6340
Epoch 120/200
98/98 [==============================] - 0s 331us/sample - loss: 3571.8035
Epoch 121/200
98/98 [==============================] - 0s 356us/sample - loss: 3428.4064
Epoch 122/200
98/98 [==============================] - 0s 326us/sample - loss: 3331.9105
Epoch 123/200
98/98 [==============================] - 0s 320us/sample - loss: 3480.6966
Epoch 124/200
98/98 [==============================] - 0s 346us/sample - loss: 3404.0719
Epoch 125/200
98/98 [==============================] - 0s 315us/sample - loss: 3177.3918
Epoch 126/200
98/98 [==============================] - 0s 326us/sample - loss: 3048.4309
Epoch 127/200
98/98 [==============================] - 0s 366us/sample - loss: 2927.4766
Epoch 128/200
98/98 [==============================] - 0s 336us/sample - loss: 2836.0170
Epoch 129/200
98/98 [==============================] - 0s 346us/sample - loss: 2717.0962
Epoch 130/200
98/98 [==============================] - 0s 325us/sample - loss: 3961.9183
Epoch 131/200
98/98 [==============================] - 0s 305us/sample - loss: 3936.9874
Epoch 132/200
98/98 [==============================] - 0s 346us/sample - loss: 4101.8395
Epoch 133/200
98/98 [==============================] - 0s 336us/sample - loss: 4144.1397
Epoch 134/200
98/98 [==============================] - 0s 307us/sample - loss: 4000.7121
Epoch 135/200
98/98 [==============================] - 0s 326us/sample - loss: 3807.1906
Epoch 136/200
98/98 [==============================] - 0s 336us/sample - loss: 3588.8518
Epoch 137/200
98/98 [==============================] - 0s 316us/sample - loss: 3422.4521
Epoch 138/200
98/98 [==============================] - 0s 326us/sample - loss: 3195.3163
Epoch 139/200
98/98 [==============================] - 0s 336us/sample - loss: 2987.9944
Epoch 140/200
98/98 [==============================] - 0s 336us/sample - loss: 2729.4287
Epoch 141/200
98/98 [==============================] - 0s 326us/sample - loss: 2509.0092
Epoch 142/200
98/98 [==============================] - 0s 325us/sample - loss: 2455.7258
Epoch 143/200
98/98 [==============================] - 0s 315us/sample - loss: 2391.3258
Epoch 144/200

98/98 [==============================] - 0s 326us/sample - loss: 2166.6358
Epoch 145/200
98/98 [==============================] - 0s 346us/sample - loss: 2330.7778
Epoch 146/200
98/98 [==============================] - 0s 336us/sample - loss: 2136.6354
Epoch 147/200
98/98 [==============================] - 0s 305us/sample - loss: 1812.7239
Epoch 148/200
98/98 [==============================] - 0s 326us/sample - loss: 2238.6188
Epoch 149/200
98/98 [==============================] - 0s 326us/sample - loss: 1672.0275
Epoch 150/200
98/98 [==============================] - 0s 339us/sample - loss: 1571.1275
Epoch 151/200
98/98 [==============================] - 0s 346us/sample - loss: 1499.9107
Epoch 152/200
98/98 [==============================] - 0s 336us/sample - loss: 1356.9595
Epoch 153/200
98/98 [==============================] - 0s 295us/sample - loss: 1232.1617
Epoch 154/200
98/98 [==============================] - 0s 356us/sample - loss: 1165.9842
Epoch 155/200
98/98 [==============================] - 0s 295us/sample - loss: 955.6710
Epoch 156/200
98/98 [==============================] - 0s 325us/sample - loss: 744.0578
Epoch 157/200
98/98 [==============================] - 0s 326us/sample - loss: 762.3415
Epoch 158/200
98/98 [==============================] - 0s 305us/sample - loss: 650.6520
Epoch 159/200
98/98 [==============================] - 0s 326us/sample - loss: 616.4088
Epoch 160/200
98/98 [==============================] - 0s 346us/sample - loss: 559.7326
Epoch 161/200
98/98 [==============================] - 0s 295us/sample - loss: 553.3784
Epoch 162/200
98/98 [==============================] - 0s 346us/sample - loss: 459.2044
Epoch 163/200
98/98 [==============================] - 0s 387us/sample - loss: 524.7487
Epoch 164/200
98/98 [==============================] - 0s 315us/sample - loss: 583.9064
Epoch 165/200
98/98 [==============================] - 0s 305us/sample - loss: 685.4971
Epoch 166/200
98/98 [==============================] - 0s 343us/sample - loss: 2118.8095
Epoch 167/200
98/98 [==============================] - 0s 315us/sample - loss: 4158.3626
Epoch 168/200
98/98 [==============================] - 0s 336us/sample - loss: 4180.2041
Epoch 169/200
98/98 [==============================] - 0s 341us/sample - loss: 3980.3658
Epoch 170/200
98/98 [==============================] - 0s 336us/sample - loss: 3962.6920
Epoch 171/200
98/98 [==============================] - 0s 346us/sample - loss: 3813.5651
Epoch 172/200
98/98 [==============================] - 0s 326us/sample - loss: 4099.1239
Epoch 173/200
98/98 [==============================] - 0s 326us/sample - loss: 3646.2513
Epoch 174/200
98/98 [==============================] - 0s 336us/sample - loss: 3505.6130
Epoch 175/200
98/98 [==============================] - 0s 356us/sample - loss: 3369.8182
Epoch 176/200
98/98 [==============================] - 0s 336us/sample - loss: 3463.9626
Epoch 177/200
98/98 [==============================] - 0s 326us/sample - loss: 3230.7084
Epoch 178/200
98/98 [==============================] - 0s 346us/sample - loss: 2933.5991
Epoch 179/200
98/98 [==============================] - 0s 315us/sample - loss: 2663.6482
Epoch 180/200
98/98 [==============================] - 0s 326us/sample - loss: 2522.2368
Epoch 181/200
98/98 [==============================] - 0s 325us/sample - loss: 2354.4591
Epoch 182/200
98/98 [==============================] - 0s 336us/sample - loss: 2345.8521
Epoch 183/200
98/98 [==============================] - 0s 325us/sample - loss: 2229.6768
Epoch 184/200
98/98 [==============================] - 0s 336us/sample - loss: 2331.4425
Epoch 185/200
98/98 [==============================] - 0s 305us/sample - loss: 2110.3268
Epoch 186/200
98/98 [==============================] - 0s 336us/sample - loss: 1880.3149
Epoch 187/200
98/98 [==============================] - 0s 336us/sample - loss: 1965.7781
Epoch 188/200
98/98 [==============================] - 0s 325us/sample - loss: 4502.7161
Epoch 189/200
98/98 [==============================] - 0s 326us/sample - loss: 17894.0716
Epoch 190/200
98/98 [==============================] - 0s 315us/sample - loss: 5190.6782
Epoch 191/200
98/98 [==============================] - 0s 315us/sample - loss: 4186.4573
Epoch 192/200
98/98 [==============================] - 0s 315us/sample - loss: 4077.1783
Epoch 193/200
98/98 [==============================] - 0s 336us/sample - loss: 3604.5585
Epoch 194/200
98/98 [==============================] - 0s 315us/sample - loss: 3497.9004
Epoch 195/200
98/98 [==============================] - 0s 326us/sample - loss: 3440.0677
Epoch 196/200
98/98 [==============================] - 0s 325us/sample - loss: 3290.9956
Epoch 197/200
98/98 [==============================] - 0s 336us/sample - loss: 3227.2586
Epoch 198/200
98/98 [==============================] - 0s 315us/sample - loss: 3224.3698
Epoch 199/200
98/98 [==============================] - 0s 326us/sample - loss: 3062.1265
Epoch 200/200
98/98 [==============================] - 0s 315us/sample - loss: 2983.2581
ILHA COMPRIDA-CENTRO-2983
Train on 98 samples
Epoch 1/200
98/98 [==============================] - 2s 19ms/sample - loss: 3844.2092
Epoch 2/200
98/98 [==============================] - 0s 356us/sample - loss: 3807.3672
Epoch 3/200
98/98 [==============================] - 0s 336us/sample - loss: 3761.4954
Epoch 4/200
98/98 [==============================] - 0s 327us/sample - loss: 3734.5985
Epoch 5/200
98/98 [==============================] - 0s 336us/sample - loss: 3688.0531
Epoch 6/200
98/98 [==============================] - 0s 336us/sample - loss: 3643.9349
Epoch 7/200
98/98 [==============================] - 0s 324us/sample - loss: 3605.6874
Epoch 8/200
98/98 [==============================] - 0s 326us/sample - loss: 3542.9708
Epoch 9/200
98/98 [==============================] - 0s 335us/sample - loss: 3571.2346
Epoch 10/200
98/98 [==============================] - 0s 326us/sample - loss: 3551.8827
Epoch 11/200
98/98 [==============================] - 0s 346us/sample - loss: 3507.6405
Epoch 12/200
98/98 [==============================] - 0s 354us/sample - loss: 3463.3712
Epoch 13/200
98/98 [==============================] - 0s 315us/sample - loss: 3416.7458
Epoch 14/200
98/98 [==============================] - 0s 336us/sample - loss: 3394.0531
Epoch 15/200
98/98 [==============================] - 0s 305us/sample - loss: 3326.1442
Epoch 16/200
98/98 [==============================] - 0s 336us/sample - loss: 3239.5510
Epoch 17/200
98/98 [==============================] - 0s 356us/sample - loss: 3222.9084
Epoch 18/200
98/98 [==============================] - 0s 336us/sample - loss: 3156.7744
Epoch 19/200
98/98 [==============================] - 0s 356us/sample - loss: 3262.0821
Epoch 20/200
98/98 [==============================] - 0s 341us/sample - loss: 3139.2008
Epoch 21/200
98/98 [==============================] - 0s 315us/sample - loss: 3142.8032
Epoch 22/200
98/98 [==============================] - 0s 397us/sample - loss: 3203.3999
Epoch 23/200
98/98 [==============================] - 0s 336us/sample - loss: 3161.6264
Epoch 24/200
98/98 [==============================] - 0s 306us/sample - loss: 3090.3629
Epoch 25/200
98/98 [==============================] - 0s 376us/sample - loss: 3046.8426
Epoch 26/200
98/98 [==============================] - 0s 346us/sample - loss: 2957.3687
Epoch 27/200
98/98 [==============================] - 0s 336us/sample - loss: 2878.2014
Epoch 28/200
98/98 [==============================] - 0s 377us/sample - loss: 2875.8596
Epoch 29/200
98/98 [==============================] - 0s 407us/sample - loss: 2982.5354
Epoch 30/200
98/98 [==============================] - 0s 366us/sample - loss: 2829.9284
Epoch 31/200
98/98 [==============================] - 0s 356us/sample - loss: 2676.3350
Epoch 32/200
98/98 [==============================] - 0s 326us/sample - loss: 2607.5083
Epoch 33/200
98/98 [==============================] - 0s 356us/sample - loss: 2549.5963
Epoch 34/200
98/98 [==============================] - 0s 356us/sample - loss: 2472.8588
Epoch 35/200
98/98 [==============================] - 0s 356us/sample - loss: 4434.0082
Epoch 36/200
98/98 [==============================] - 0s 346us/sample - loss: 2808.1535
Epoch 37/200
98/98 [==============================] - 0s 377us/sample - loss: 2886.3653
Epoch 38/200
98/98 [==============================] - 0s 366us/sample - loss: 3199.3268
Epoch 39/200
98/98 [==============================] - 0s 362us/sample - loss: 2973.4749
Epoch 40/200
98/98 [==============================] - 0s 356us/sample - loss: 3217.3008
Epoch 41/200
98/98 [==============================] - 0s 326us/sample - loss: 3758.9243
Epoch 42/200
98/98 [==============================] - 0s 346us/sample - loss: 2666.7733
Epoch 43/200
98/98 [==============================] - 0s 315us/sample - loss: 2827.2158
Epoch 44/200
98/98 [==============================] - 0s 372us/sample - loss: 2889.4366
Epoch 45/200
98/98 [==============================] - 0s 351us/sample - loss: 2695.8730
Epoch 46/200
98/98 [==============================] - 0s 379us/sample - loss: 2675.0942
Epoch 47/200
98/98 [==============================] - 0s 349us/sample - loss: 2519.8550
Epoch 48/200
98/98 [==============================] - 0s 346us/sample - loss: 2430.2886
Epoch 49/200
98/98 [==============================] - 0s 407us/sample - loss: 2350.5842
Epoch 50/200
98/98 [==============================] - 0s 346us/sample - loss: 2310.3733
Epoch 51/200
98/98 [==============================] - 0s 305us/sample - loss: 2260.9937
Epoch 52/200
98/98 [==============================] - 0s 336us/sample - loss: 2173.9436
Epoch 53/200
98/98 [==============================] - 0s 336us/sample - loss: 2086.7806
Epoch 54/200
98/98 [==============================] - 0s 336us/sample - loss: 2024.4921
Epoch 55/200
98/98 [==============================] - 0s 325us/sample - loss: 1979.8602
Epoch 56/200
98/98 [==============================] - 0s 344us/sample - loss: 1889.3975
Epoch 57/200
98/98 [==============================] - 0s 351us/sample - loss: 1818.0537
Epoch 58/200
98/98 [==============================] - 0s 336us/sample - loss: 2677.4125
Epoch 59/200
98/98 [==============================] - 0s 301us/sample - loss: 4684.1984
Epoch 60/200
98/98 [==============================] - 0s 315us/sample - loss: 2648.1790
Epoch 61/200
98/98 [==============================] - 0s 348us/sample - loss: 2303.3403
Epoch 62/200
98/98 [==============================] - 0s 314us/sample - loss: 2244.4326
Epoch 63/200
98/98 [==============================] - 0s 326us/sample - loss: 2228.6983
Epoch 64/200
98/98 [==============================] - 0s 331us/sample - loss: 2128.3897
Epoch 65/200
98/98 [==============================] - 0s 295us/sample - loss: 2095.9226
Epoch 66/200
98/98 [==============================] - 0s 346us/sample - loss: 1967.6574
Epoch 67/200
98/98 [==============================] - 0s 297us/sample - loss: 1899.3580
Epoch 68/200
98/98 [==============================] - 0s 320us/sample - loss: 1855.4126
Epoch 69/200
98/98 [==============================] - 0s 326us/sample - loss: 1805.8107
Epoch 70/200
98/98 [==============================] - 0s 351us/sample - loss: 1734.5476
Epoch 71/200
98/98 [==============================] - 0s 315us/sample - loss: 2222.7759
Epoch 72/200
98/98 [==============================] - 0s 306us/sample - loss: 2295.0624
Epoch 73/200
98/98 [==============================] - 0s 336us/sample - loss: 2126.0395
Epoch 74/200
98/98 [==============================] - 0s 336us/sample - loss: 2041.4509
Epoch 75/200
98/98 [==============================] - 0s 326us/sample - loss: 1939.2589
Epoch 76/200
98/98 [==============================] - 0s 336us/sample - loss: 1842.3296
Epoch 77/200
98/98 [==============================] - 0s 315us/sample - loss: 1734.1162
Epoch 78/200
98/98 [==============================] - 0s 326us/sample - loss: 1619.6824
Epoch 79/200
98/98 [==============================] - 0s 326us/sample - loss: 1604.3917
Epoch 80/200
98/98 [==============================] - 0s 356us/sample - loss: 1589.3979
Epoch 81/200
98/98 [==============================] - 0s 336us/sample - loss: 1494.6213
Epoch 82/200
98/98 [==============================] - 0s 305us/sample - loss: 1304.8878
Epoch 83/200
98/98 [==============================] - 0s 315us/sample - loss: 1268.5324
Epoch 84/200
98/98 [==============================] - 0s 346us/sample - loss: 1231.9682
Epoch 85/200
98/98 [==============================] - 0s 315us/sample - loss: 1172.0305
Epoch 86/200
98/98 [==============================] - 0s 356us/sample - loss: 1134.0020
Epoch 87/200
98/98 [==============================] - 0s 336us/sample - loss: 1112.0981
Epoch 88/200
98/98 [==============================] - 0s 336us/sample - loss: 1064.5347
Epoch 89/200
98/98 [==============================] - 0s 336us/sample - loss: 1048.9084
Epoch 90/200
98/98 [==============================] - 0s 315us/sample - loss: 1077.0693
Epoch 91/200
98/98 [==============================] - 0s 336us/sample - loss: 1002.1926
Epoch 92/200
98/98 [==============================] - 0s 315us/sample - loss: 998.7982
Epoch 93/200
98/98 [==============================] - 0s 336us/sample - loss: 949.3897
Epoch 94/200
98/98 [==============================] - 0s 346us/sample - loss: 994.2416
Epoch 95/200
98/98 [==============================] - 0s 312us/sample - loss: 934.8829
Epoch 96/200
98/98 [==============================] - 0s 315us/sample - loss: 1006.2315
Epoch 97/200
98/98 [==============================] - 0s 325us/sample - loss: 1139.2206
Epoch 98/200
98/98 [==============================] - 0s 315us/sample - loss: 1524.0827
Epoch 99/200
98/98 [==============================] - 0s 315us/sample - loss: 1258.2881
Epoch 100/200
98/98 [==============================] - 0s 342us/sample - loss: 1238.3072
Epoch 101/200
98/98 [==============================] - 0s 295us/sample - loss: 1099.9657
Epoch 102/200
98/98 [==============================] - 0s 326us/sample - loss: 1050.3140
Epoch 103/200
98/98 [==============================] - 0s 326us/sample - loss: 1024.3916
Epoch 104/200
98/98 [==============================] - 0s 336us/sample - loss: 1064.1912
Epoch 105/200
98/98 [==============================] - 0s 356us/sample - loss: 1047.8837
Epoch 106/200
98/98 [==============================] - 0s 325us/sample - loss: 1000.6005
Epoch 107/200
98/98 [==============================] - 0s 302us/sample - loss: 1064.0831
Epoch 108/200
98/98 [==============================] - 0s 315us/sample - loss: 873.2884
Epoch 109/200
98/98 [==============================] - 0s 315us/sample - loss: 871.3318
Epoch 110/200
98/98 [==============================] - 0s 366us/sample - loss: 1240.4379
Epoch 111/200
98/98 [==============================] - 0s 324us/sample - loss: 1509.1204
Epoch 112/200
98/98 [==============================] - 0s 305us/sample - loss: 1259.6807
Epoch 113/200
98/98 [==============================] - 0s 295us/sample - loss: 1072.8987
Epoch 114/200
98/98 [==============================] - 0s 336us/sample - loss: 1044.2018
Epoch 115/200
98/98 [==============================] - 0s 326us/sample - loss: 1021.4454
Epoch 116/200
98/98 [==============================] - 0s 343us/sample - loss: 951.6421
Epoch 117/200
98/98 [==============================] - 0s 336us/sample - loss: 893.2351
Epoch 118/200
98/98 [==============================] - 0s 326us/sample - loss: 867.3599
Epoch 119/200
98/98 [==============================] - 0s 324us/sample - loss: 824.6818
Epoch 120/200
98/98 [==============================] - 0s 346us/sample - loss: 779.3675
Epoch 121/200
98/98 [==============================] - 0s 346us/sample - loss: 756.9182
Epoch 122/200
98/98 [==============================] - 0s 351us/sample - loss: 719.9435
Epoch 123/200
98/98 [==============================] - 0s 336us/sample - loss: 727.2889
Epoch 124/200
98/98 [==============================] - 0s 336us/sample - loss: 682.0737
Epoch 125/200
98/98 [==============================] - 0s 316us/sample - loss: 673.3147
Epoch 126/200
98/98 [==============================] - 0s 337us/sample - loss: 647.2832
Epoch 127/200
98/98 [==============================] - 0s 305us/sample - loss: 694.3509
Epoch 128/200
98/98 [==============================] - 0s 331us/sample - loss: 726.9519
Epoch 129/200

98/98 [==============================] - 0s 377us/sample - loss: 721.3026
Epoch 130/200
98/98 [==============================] - 0s 325us/sample - loss: 657.2451
Epoch 131/200
98/98 [==============================] - 0s 295us/sample - loss: 682.7225
Epoch 132/200
98/98 [==============================] - 0s 328us/sample - loss: 726.3183
Epoch 133/200
98/98 [==============================] - 0s 326us/sample - loss: 696.0430
Epoch 134/200
98/98 [==============================] - 0s 377us/sample - loss: 661.4836
Epoch 135/200
98/98 [==============================] - 0s 326us/sample - loss: 639.3951
Epoch 136/200
98/98 [==============================] - 0s 315us/sample - loss: 618.2580
Epoch 137/200
98/98 [==============================] - 0s 305us/sample - loss: 604.5516
Epoch 138/200
98/98 [==============================] - 0s 326us/sample - loss: 590.3808
Epoch 139/200
98/98 [==============================] - 0s 325us/sample - loss: 587.4546
Epoch 140/200
98/98 [==============================] - 0s 356us/sample - loss: 606.9468
Epoch 141/200
98/98 [==============================] - 0s 336us/sample - loss: 649.3302
Epoch 142/200
98/98 [==============================] - 0s 346us/sample - loss: 609.9074
Epoch 143/200
98/98 [==============================] - 0s 295us/sample - loss: 596.0017
Epoch 144/200
98/98 [==============================] - 0s 315us/sample - loss: 590.7776
Epoch 145/200
98/98 [==============================] - 0s 326us/sample - loss: 585.9968
Epoch 146/200
98/98 [==============================] - 0s 325us/sample - loss: 580.2041
Epoch 147/200
98/98 [==============================] - 0s 356us/sample - loss: 565.3501
Epoch 148/200
98/98 [==============================] - 0s 346us/sample - loss: 567.9514
Epoch 149/200
98/98 [==============================] - 0s 305us/sample - loss: 562.4388
Epoch 150/200
98/98 [==============================] - 0s 326us/sample - loss: 570.9238
Epoch 151/200
98/98 [==============================] - 0s 336us/sample - loss: 585.9646
Epoch 152/200
98/98 [==============================] - 0s 346us/sample - loss: 615.8910
Epoch 153/200
98/98 [==============================] - 0s 321us/sample - loss: 615.8260
Epoch 154/200
98/98 [==============================] - 0s 336us/sample - loss: 593.7088
Epoch 155/200
98/98 [==============================] - 0s 305us/sample - loss: 578.8626
Epoch 156/200
98/98 [==============================] - 0s 326us/sample - loss: 587.3792
Epoch 157/200
98/98 [==============================] - 0s 305us/sample - loss: 649.2169
Epoch 158/200
98/98 [==============================] - 0s 336us/sample - loss: 706.5319
Epoch 159/200
98/98 [==============================] - 0s 346us/sample - loss: 706.3182
Epoch 160/200
98/98 [==============================] - 0s 331us/sample - loss: 625.9734
Epoch 161/200
98/98 [==============================] - 0s 326us/sample - loss: 620.3641
Epoch 162/200
98/98 [==============================] - 0s 315us/sample - loss: 571.6553
Epoch 163/200
98/98 [==============================] - 0s 315us/sample - loss: 594.4531
Epoch 164/200
98/98 [==============================] - 0s 326us/sample - loss: 606.0499
Epoch 165/200
98/98 [==============================] - 0s 326us/sample - loss: 595.1781
Epoch 166/200
98/98 [==============================] - 0s 325us/sample - loss: 592.6953
Epoch 167/200
98/98 [==============================] - 0s 350us/sample - loss: 563.0828
Epoch 168/200
98/98 [==============================] - 0s 335us/sample - loss: 552.6050
Epoch 169/200
98/98 [==============================] - 0s 326us/sample - loss: 560.5058
Epoch 170/200
98/98 [==============================] - 0s 346us/sample - loss: 551.2141
Epoch 171/200
98/98 [==============================] - 0s 346us/sample - loss: 555.6934
Epoch 172/200
98/98 [==============================] - 0s 346us/sample - loss: 547.6721
Epoch 173/200
98/98 [==============================] - 0s 336us/sample - loss: 548.9361
Epoch 174/200
98/98 [==============================] - 0s 326us/sample - loss: 557.1715
Epoch 175/200
98/98 [==============================] - 0s 315us/sample - loss: 559.7139
Epoch 176/200
98/98 [==============================] - 0s 295us/sample - loss: 565.0711
Epoch 177/200
98/98 [==============================] - 0s 346us/sample - loss: 565.2067
Epoch 178/200
98/98 [==============================] - 0s 295us/sample - loss: 579.1593
Epoch 179/200
98/98 [==============================] - 0s 305us/sample - loss: 576.9063
Epoch 180/200
98/98 [==============================] - 0s 326us/sample - loss: 572.8126
Epoch 181/200
98/98 [==============================] - 0s 346us/sample - loss: 562.3741
Epoch 182/200
98/98 [==============================] - 0s 315us/sample - loss: 563.0032
Epoch 183/200
98/98 [==============================] - 0s 315us/sample - loss: 647.0733
Epoch 184/200
98/98 [==============================] - 0s 331us/sample - loss: 621.3789
Epoch 185/200
98/98 [==============================] - 0s 315us/sample - loss: 879.9420
Epoch 186/200
98/98 [==============================] - 0s 326us/sample - loss: 1337.1466
Epoch 187/200
98/98 [==============================] - 0s 325us/sample - loss: 1362.7401
Epoch 188/200
98/98 [==============================] - 0s 326us/sample - loss: 1627.5024
Epoch 189/200
98/98 [==============================] - 0s 346us/sample - loss: 1235.2863
Epoch 190/200
98/98 [==============================] - 0s 356us/sample - loss: 4772.4316
Epoch 191/200
98/98 [==============================] - 0s 316us/sample - loss: 3752.1527
Epoch 192/200
98/98 [==============================] - 0s 315us/sample - loss: 3222.5920
Epoch 193/200
98/98 [==============================] - 0s 336us/sample - loss: 3266.7468
Epoch 194/200
98/98 [==============================] - 0s 315us/sample - loss: 3072.2375
Epoch 195/200
98/98 [==============================] - 0s 350us/sample - loss: 3168.1868
Epoch 196/200
98/98 [==============================] - 0s 345us/sample - loss: 3054.3185
Epoch 197/200
98/98 [==============================] - 0s 315us/sample - loss: 2936.4714
Epoch 198/200
98/98 [==============================] - 0s 315us/sample - loss: 2886.6608
Epoch 199/200
98/98 [==============================] - 0s 326us/sample - loss: 2856.1402
Epoch 200/200
98/98 [==============================] - 0s 336us/sample - loss: 2895.6443
ILHA COMPRIDA-PONTAL-2896
Train on 98 samples
Epoch 1/200
98/98 [==============================] - 2s 18ms/sample - loss: 25911.3731
Epoch 2/200
98/98 [==============================] - 0s 346us/sample - loss: 24877.0111
Epoch 3/200
98/98 [==============================] - 0s 326us/sample - loss: 23884.0713
Epoch 4/200
98/98 [==============================] - 0s 336us/sample - loss: 23213.3021
Epoch 5/200
98/98 [==============================] - 0s 325us/sample - loss: 22353.2728
Epoch 6/200
98/98 [==============================] - 0s 315us/sample - loss: 21833.2085
Epoch 7/200
98/98 [==============================] - 0s 326us/sample - loss: 21159.9394
Epoch 8/200
98/98 [==============================] - 0s 336us/sample - loss: 20752.6799
Epoch 9/200
98/98 [==============================] - 0s 336us/sample - loss: 20293.9166
Epoch 10/200
98/98 [==============================] - 0s 326us/sample - loss: 20022.6105
Epoch 11/200
98/98 [==============================] - 0s 326us/sample - loss: 19829.1629
Epoch 12/200
98/98 [==============================] - 0s 336us/sample - loss: 19581.3803
Epoch 13/200
98/98 [==============================] - 0s 325us/sample - loss: 19299.6658
Epoch 14/200
98/98 [==============================] - 0s 336us/sample - loss: 19064.7194
Epoch 15/200
98/98 [==============================] - 0s 346us/sample - loss: 18793.4702
Epoch 16/200
98/98 [==============================] - 0s 305us/sample - loss: 18321.8787
Epoch 17/200
98/98 [==============================] - 0s 315us/sample - loss: 18399.7888
Epoch 18/200
98/98 [==============================] - 0s 331us/sample - loss: 17639.4448
Epoch 19/200
98/98 [==============================] - 0s 295us/sample - loss: 17780.8919
Epoch 20/200
98/98 [==============================] - 0s 311us/sample - loss: 17208.0261
Epoch 21/200
98/98 [==============================] - 0s 315us/sample - loss: 16777.7257
Epoch 22/200
98/98 [==============================] - 0s 325us/sample - loss: 16756.6484
Epoch 23/200
98/98 [==============================] - 0s 336us/sample - loss: 16442.0967
Epoch 24/200
98/98 [==============================] - 0s 326us/sample - loss: 17197.1613
Epoch 25/200
98/98 [==============================] - 0s 305us/sample - loss: 16683.3739
Epoch 26/200
98/98 [==============================] - 0s 326us/sample - loss: 16006.1513
Epoch 27/200
98/98 [==============================] - 0s 326us/sample - loss: 15683.1032
Epoch 28/200
98/98 [==============================] - 0s 315us/sample - loss: 15853.7606
Epoch 29/200
98/98 [==============================] - 0s 325us/sample - loss: 15059.2962
Epoch 30/200
98/98 [==============================] - 0s 326us/sample - loss: 14338.3276
Epoch 31/200
98/98 [==============================] - 0s 326us/sample - loss: 14259.7137
Epoch 32/200
98/98 [==============================] - 0s 315us/sample - loss: 13752.9833
Epoch 33/200
98/98 [==============================] - 0s 326us/sample - loss: 13370.8582
Epoch 34/200
98/98 [==============================] - 0s 336us/sample - loss: 13644.5512
Epoch 35/200
98/98 [==============================] - 0s 326us/sample - loss: 13575.5801
Epoch 36/200
98/98 [==============================] - 0s 332us/sample - loss: 12503.4248
Epoch 37/200
98/98 [==============================] - 0s 354us/sample - loss: 12216.9265
Epoch 38/200
98/98 [==============================] - 0s 356us/sample - loss: 13091.9833
Epoch 39/200
98/98 [==============================] - 0s 346us/sample - loss: 13104.3485
Epoch 40/200
98/98 [==============================] - 0s 354us/sample - loss: 12184.5717
Epoch 41/200
98/98 [==============================] - 0s 346us/sample - loss: 11049.0014
Epoch 42/200
98/98 [==============================] - 0s 336us/sample - loss: 10602.6324
Epoch 43/200
98/98 [==============================] - 0s 346us/sample - loss: 10062.8243
Epoch 44/200
98/98 [==============================] - 0s 341us/sample - loss: 9633.9957
Epoch 45/200
98/98 [==============================] - 0s 366us/sample - loss: 8721.1375
Epoch 46/200
98/98 [==============================] - 0s 356us/sample - loss: 9238.9169
Epoch 47/200
98/98 [==============================] - 0s 305us/sample - loss: 38091.9372
Epoch 48/200
98/98 [==============================] - 0s 326us/sample - loss: 29728.0630
Epoch 49/200
98/98 [==============================] - 0s 314us/sample - loss: 21370.7974
Epoch 50/200
98/98 [==============================] - 0s 326us/sample - loss: 14485.1522
Epoch 51/200
98/98 [==============================] - 0s 326us/sample - loss: 13232.6014
Epoch 52/200
98/98 [==============================] - 0s 356us/sample - loss: 17262.6416
Epoch 53/200
98/98 [==============================] - 0s 346us/sample - loss: 15079.1218
Epoch 54/200
98/98 [==============================] - 0s 346us/sample - loss: 13564.0529
Epoch 55/200
98/98 [==============================] - 0s 387us/sample - loss: 13264.0954
Epoch 56/200
98/98 [==============================] - 0s 387us/sample - loss: 13720.0435
Epoch 57/200
98/98 [==============================] - 0s 366us/sample - loss: 13023.9435
Epoch 58/200
98/98 [==============================] - 0s 346us/sample - loss: 12554.4884
Epoch 59/200
98/98 [==============================] - 0s 352us/sample - loss: 12013.5413
Epoch 60/200
98/98 [==============================] - 0s 366us/sample - loss: 11591.5638
Epoch 61/200
98/98 [==============================] - 0s 346us/sample - loss: 10814.6679
Epoch 62/200
98/98 [==============================] - ETA: 0s - loss: 4156.74 - 0s 336us/sample - loss: 10448.2200
Epoch 63/200
98/98 [==============================] - 0s 326us/sample - loss: 10363.2104
Epoch 64/200
98/98 [==============================] - 0s 315us/sample - loss: 10536.7883
Epoch 65/200
98/98 [==============================] - 0s 326us/sample - loss: 10452.6717
Epoch 66/200
98/98 [==============================] - 0s 366us/sample - loss: 10311.2999
Epoch 67/200
98/98 [==============================] - 0s 315us/sample - loss: 9984.9468
Epoch 68/200
98/98 [==============================] - 0s 326us/sample - loss: 9804.3889
Epoch 69/200
98/98 [==============================] - 0s 315us/sample - loss: 9247.4455
Epoch 70/200
98/98 [==============================] - 0s 315us/sample - loss: 9116.7588
Epoch 71/200
98/98 [==============================] - 0s 336us/sample - loss: 10006.8754
Epoch 72/200
98/98 [==============================] - 0s 305us/sample - loss: 9892.8219
Epoch 73/200
98/98 [==============================] - 0s 316us/sample - loss: 9174.2907
Epoch 74/200
98/98 [==============================] - 0s 336us/sample - loss: 8692.4420
Epoch 75/200
98/98 [==============================] - 0s 326us/sample - loss: 9376.3858
Epoch 76/200
98/98 [==============================] - 0s 315us/sample - loss: 8606.8112
Epoch 77/200
98/98 [==============================] - 0s 315us/sample - loss: 8161.5355
Epoch 78/200
98/98 [==============================] - 0s 346us/sample - loss: 8003.1759
Epoch 79/200
98/98 [==============================] - 0s 336us/sample - loss: 7840.2573
Epoch 80/200
98/98 [==============================] - 0s 346us/sample - loss: 7865.1661
Epoch 81/200
98/98 [==============================] - 0s 341us/sample - loss: 7135.4059
Epoch 82/200
98/98 [==============================] - 0s 316us/sample - loss: 7189.3190
Epoch 83/200
98/98 [==============================] - 0s 336us/sample - loss: 7230.1846
Epoch 84/200
98/98 [==============================] - 0s 356us/sample - loss: 6765.2019
Epoch 85/200
98/98 [==============================] - 0s 315us/sample - loss: 6452.9063
Epoch 86/200
98/98 [==============================] - 0s 326us/sample - loss: 6012.9267
Epoch 87/200
98/98 [==============================] - 0s 324us/sample - loss: 5678.2797
Epoch 88/200
98/98 [==============================] - 0s 305us/sample - loss: 6064.3730
Epoch 89/200
98/98 [==============================] - 0s 331us/sample - loss: 6605.5340
Epoch 90/200
98/98 [==============================] - 0s 346us/sample - loss: 6814.9372
Epoch 91/200
98/98 [==============================] - 0s 346us/sample - loss: 6572.8516
Epoch 92/200
98/98 [==============================] - 0s 336us/sample - loss: 6213.2791
Epoch 93/200
98/98 [==============================] - 0s 356us/sample - loss: 6264.9075
Epoch 94/200
98/98 [==============================] - 0s 315us/sample - loss: 6017.9740
Epoch 95/200
98/98 [==============================] - 0s 316us/sample - loss: 5637.1040
Epoch 96/200
98/98 [==============================] - 0s 336us/sample - loss: 5571.9355
Epoch 97/200
98/98 [==============================] - 0s 333us/sample - loss: 4975.0930
Epoch 98/200
98/98 [==============================] - 0s 326us/sample - loss: 6282.3917
Epoch 99/200
98/98 [==============================] - 0s 317us/sample - loss: 5871.3486
Epoch 100/200
98/98 [==============================] - 0s 325us/sample - loss: 5449.2720
Epoch 101/200
98/98 [==============================] - 0s 346us/sample - loss: 5380.1856
Epoch 102/200
98/98 [==============================] - 0s 341us/sample - loss: 4100.5528
Epoch 103/200
98/98 [==============================] - 0s 315us/sample - loss: 4990.4435
Epoch 104/200
98/98 [==============================] - 0s 336us/sample - loss: 4697.6346
Epoch 105/200
98/98 [==============================] - 0s 326us/sample - loss: 4125.1433
Epoch 106/200
98/98 [==============================] - 0s 315us/sample - loss: 4134.5344
Epoch 107/200
98/98 [==============================] - 0s 356us/sample - loss: 4870.9785
Epoch 108/200
98/98 [==============================] - 0s 326us/sample - loss: 6138.1685
Epoch 109/200
98/98 [==============================] - 0s 387us/sample - loss: 5842.3954
Epoch 110/200
98/98 [==============================] - 0s 377us/sample - loss: 5125.4374
Epoch 111/200
98/98 [==============================] - 0s 326us/sample - loss: 4431.0269
Epoch 112/200
98/98 [==============================] - 0s 326us/sample - loss: 4541.5372
Epoch 113/200

98/98 [==============================] - 0s 326us/sample - loss: 4174.0906
Epoch 114/200
98/98 [==============================] - 0s 326us/sample - loss: 3916.9077
Epoch 115/200
98/98 [==============================] - 0s 382us/sample - loss: 3407.2655
Epoch 116/200
98/98 [==============================] - 0s 356us/sample - loss: 3191.2192
Epoch 117/200
98/98 [==============================] - 0s 324us/sample - loss: 3040.6183
Epoch 118/200
98/98 [==============================] - 0s 336us/sample - loss: 2729.5633
Epoch 119/200
98/98 [==============================] - 0s 326us/sample - loss: 3157.8201
Epoch 120/200
98/98 [==============================] - 0s 346us/sample - loss: 3058.6569
Epoch 121/200
98/98 [==============================] - 0s 336us/sample - loss: 2377.2391
Epoch 122/200
98/98 [==============================] - 0s 326us/sample - loss: 10109.8767
Epoch 123/200
98/98 [==============================] - 0s 346us/sample - loss: 7133.8346
Epoch 124/200
98/98 [==============================] - 0s 315us/sample - loss: 10576.4733
Epoch 125/200
98/98 [==============================] - 0s 331us/sample - loss: 9260.7900
Epoch 126/200
98/98 [==============================] - 0s 366us/sample - loss: 8289.8446
Epoch 127/200
98/98 [==============================] - 0s 315us/sample - loss: 8556.3838
Epoch 128/200
98/98 [==============================] - 0s 326us/sample - loss: 8469.7506
Epoch 129/200
98/98 [==============================] - 0s 315us/sample - loss: 9103.7345
Epoch 130/200
98/98 [==============================] - 0s 315us/sample - loss: 7981.5927
Epoch 131/200
98/98 [==============================] - 0s 356us/sample - loss: 7939.1219
Epoch 132/200
98/98 [==============================] - 0s 315us/sample - loss: 7702.4648
Epoch 133/200
98/98 [==============================] - 0s 326us/sample - loss: 8840.0181
Epoch 134/200
98/98 [==============================] - 0s 325us/sample - loss: 7996.6301
Epoch 135/200
98/98 [==============================] - 0s 316us/sample - loss: 6751.8109
Epoch 136/200
98/98 [==============================] - 0s 315us/sample - loss: 6466.6457
Epoch 137/200
98/98 [==============================] - 0s 315us/sample - loss: 6300.5527
Epoch 138/200
98/98 [==============================] - 0s 326us/sample - loss: 7517.1208
Epoch 139/200
98/98 [==============================] - 0s 305us/sample - loss: 6539.7854
Epoch 140/200
98/98 [==============================] - 0s 336us/sample - loss: 7042.8345
Epoch 141/200
98/98 [==============================] - 0s 315us/sample - loss: 8640.3577
Epoch 142/200
98/98 [==============================] - 0s 326us/sample - loss: 40202.4330
Epoch 143/200
98/98 [==============================] - 0s 326us/sample - loss: 16583.2932
Epoch 144/200
98/98 [==============================] - 0s 328us/sample - loss: 16894.9858
Epoch 145/200
98/98 [==============================] - 0s 315us/sample - loss: 13564.2874
Epoch 146/200
98/98 [==============================] - 0s 336us/sample - loss: 10667.9935
Epoch 147/200
98/98 [==============================] - 0s 315us/sample - loss: 11889.0913
Epoch 148/200
98/98 [==============================] - 0s 338us/sample - loss: 11956.4377
Epoch 149/200
98/98 [==============================] - 0s 325us/sample - loss: 10471.4955
Epoch 150/200
98/98 [==============================] - 0s 377us/sample - loss: 10053.6607
Epoch 151/200
98/98 [==============================] - 0s 326us/sample - loss: 9259.4290
Epoch 152/200
98/98 [==============================] - 0s 326us/sample - loss: 8621.2676
Epoch 153/200
98/98 [==============================] - 0s 326us/sample - loss: 8001.8018
Epoch 154/200
98/98 [==============================] - 0s 326us/sample - loss: 7132.3415
Epoch 155/200
98/98 [==============================] - 0s 315us/sample - loss: 6593.0585
Epoch 156/200
98/98 [==============================] - 0s 326us/sample - loss: 5706.5507
Epoch 157/200
98/98 [==============================] - 0s 366us/sample - loss: 4941.9638
Epoch 158/200
98/98 [==============================] - 0s 356us/sample - loss: 4460.8157
Epoch 159/200
98/98 [==============================] - 0s 325us/sample - loss: 4286.4974
Epoch 160/200
98/98 [==============================] - 0s 315us/sample - loss: 4058.0524
Epoch 161/200
98/98 [==============================] - 0s 336us/sample - loss: 4411.4283
Epoch 162/200
98/98 [==============================] - 0s 305us/sample - loss: 4241.5116
Epoch 163/200
98/98 [==============================] - 0s 315us/sample - loss: 3739.4555
Epoch 164/200
98/98 [==============================] - 0s 336us/sample - loss: 3394.0075
Epoch 165/200
98/98 [==============================] - 0s 326us/sample - loss: 3488.1006
Epoch 166/200
98/98 [==============================] - 0s 326us/sample - loss: 2998.4051
Epoch 167/200
98/98 [==============================] - 0s 336us/sample - loss: 3042.4043
Epoch 168/200
98/98 [==============================] - 0s 346us/sample - loss: 3006.8757
Epoch 169/200
98/98 [==============================] - 0s 356us/sample - loss: 2818.4622
Epoch 170/200
98/98 [==============================] - 0s 346us/sample - loss: 2642.9345
Epoch 171/200
98/98 [==============================] - 0s 326us/sample - loss: 2437.8812
Epoch 172/200
98/98 [==============================] - 0s 346us/sample - loss: 2383.9755
Epoch 173/200
98/98 [==============================] - 0s 336us/sample - loss: 2191.0519
Epoch 174/200
98/98 [==============================] - 0s 325us/sample - loss: 2078.8755
Epoch 175/200
98/98 [==============================] - 0s 336us/sample - loss: 2169.7133
Epoch 176/200
98/98 [==============================] - 0s 346us/sample - loss: 1994.8543
Epoch 177/200
98/98 [==============================] - 0s 331us/sample - loss: 1906.9069
Epoch 178/200
98/98 [==============================] - 0s 387us/sample - loss: 1931.2573
Epoch 179/200
98/98 [==============================] - 0s 326us/sample - loss: 1620.4447
Epoch 180/200
98/98 [==============================] - 0s 336us/sample - loss: 1508.0730
Epoch 181/200
98/98 [==============================] - 0s 326us/sample - loss: 1687.5584
Epoch 182/200
98/98 [==============================] - 0s 336us/sample - loss: 1621.2744
Epoch 183/200
98/98 [==============================] - 0s 314us/sample - loss: 1491.6015
Epoch 184/200
98/98 [==============================] - 0s 336us/sample - loss: 1647.9472
Epoch 185/200
98/98 [==============================] - 0s 336us/sample - loss: 1341.1900
Epoch 186/200
98/98 [==============================] - 0s 336us/sample - loss: 1338.3944
Epoch 187/200
98/98 [==============================] - 0s 336us/sample - loss: 1401.3968
Epoch 188/200
98/98 [==============================] - 0s 326us/sample - loss: 1308.9877
Epoch 189/200
98/98 [==============================] - 0s 321us/sample - loss: 1198.4379
Epoch 190/200
98/98 [==============================] - 0s 315us/sample - loss: 1129.3300
Epoch 191/200
98/98 [==============================] - 0s 346us/sample - loss: 1196.1518
Epoch 192/200
98/98 [==============================] - 0s 323us/sample - loss: 1213.7592
Epoch 193/200
98/98 [==============================] - 0s 336us/sample - loss: 1488.2554
Epoch 194/200
98/98 [==============================] - 0s 356us/sample - loss: 2282.9860
Epoch 195/200
98/98 [==============================] - 0s 311us/sample - loss: 4999.0186
Epoch 196/200
98/98 [==============================] - 0s 326us/sample - loss: 4346.6573
Epoch 197/200
98/98 [==============================] - 0s 336us/sample - loss: 4402.3208
Epoch 198/200
98/98 [==============================] - 0s 336us/sample - loss: 3603.9420
Epoch 199/200
98/98 [==============================] - 0s 325us/sample - loss: 3338.9724
Epoch 200/200
98/98 [==============================] - 0s 336us/sample - loss: 2930.7762
ILHA COMPRIDA-PRAINHA (BALSA)-2931
Train on 93 samples
Epoch 1/200
93/93 [==============================] - 2s 20ms/sample - loss: 2056.1819
Epoch 2/200
93/93 [==============================] - 0s 268us/sample - loss: 2045.1906
Epoch 3/200
93/93 [==============================] - 0s 279us/sample - loss: 2031.8507
Epoch 4/200
93/93 [==============================] - 0s 301us/sample - loss: 2017.9966
Epoch 5/200
93/93 [==============================] - 0s 257us/sample - loss: 2000.3731
Epoch 6/200
93/93 [==============================] - 0s 279us/sample - loss: 1986.7625
Epoch 7/200
93/93 [==============================] - 0s 247us/sample - loss: 1982.0598
Epoch 8/200
93/93 [==============================] - 0s 264us/sample - loss: 1975.8711
Epoch 9/200
93/93 [==============================] - 0s 276us/sample - loss: 1969.7002
Epoch 10/200
93/93 [==============================] - 0s 268us/sample - loss: 1962.5331
Epoch 11/200
93/93 [==============================] - 0s 311us/sample - loss: 1951.7411
Epoch 12/200
93/93 [==============================] - 0s 247us/sample - loss: 1946.2308
Epoch 13/200
93/93 [==============================] - 0s 290us/sample - loss: 1936.8460
Epoch 14/200
93/93 [==============================] - 0s 279us/sample - loss: 1925.1931
Epoch 15/200
93/93 [==============================] - 0s 268us/sample - loss: 1907.4051
Epoch 16/200
93/93 [==============================] - 0s 257us/sample - loss: 1886.3570
Epoch 17/200
93/93 [==============================] - 0s 257us/sample - loss: 1869.6753
Epoch 18/200
93/93 [==============================] - 0s 279us/sample - loss: 1837.4398
Epoch 19/200
93/93 [==============================] - 0s 268us/sample - loss: 1834.4144
Epoch 20/200
93/93 [==============================] - 0s 257us/sample - loss: 1796.2600
Epoch 21/200
93/93 [==============================] - 0s 300us/sample - loss: 1754.6587
Epoch 22/200
93/93 [==============================] - 0s 268us/sample - loss: 1715.8282
Epoch 23/200
93/93 [==============================] - 0s 248us/sample - loss: 1689.1046
Epoch 24/200
93/93 [==============================] - 0s 279us/sample - loss: 1623.3014
Epoch 25/200
93/93 [==============================] - 0s 279us/sample - loss: 1584.3521
Epoch 26/200
93/93 [==============================] - 0s 279us/sample - loss: 1552.9258
Epoch 27/200
93/93 [==============================] - 0s 268us/sample - loss: 1515.9069
Epoch 28/200
93/93 [==============================] - 0s 257us/sample - loss: 1451.3843
Epoch 29/200
93/93 [==============================] - 0s 290us/sample - loss: 1421.3263
Epoch 30/200
93/93 [==============================] - 0s 247us/sample - loss: 1386.8168
Epoch 31/200
93/93 [==============================] - 0s 268us/sample - loss: 1331.0963
Epoch 32/200
93/93 [==============================] - 0s 257us/sample - loss: 1324.9302
Epoch 33/200
93/93 [==============================] - 0s 301us/sample - loss: 1277.3419
Epoch 34/200
93/93 [==============================] - 0s 257us/sample - loss: 1241.5857
Epoch 35/200
93/93 [==============================] - 0s 247us/sample - loss: 1237.6340
Epoch 36/200
93/93 [==============================] - 0s 264us/sample - loss: 1183.2218
Epoch 37/200
93/93 [==============================] - 0s 279us/sample - loss: 1144.6538
Epoch 38/200
93/93 [==============================] - 0s 268us/sample - loss: 1107.7716
Epoch 39/200
93/93 [==============================] - 0s 247us/sample - loss: 1100.2229
Epoch 40/200
93/93 [==============================] - 0s 257us/sample - loss: 1047.8834
Epoch 41/200
93/93 [==============================] - 0s 257us/sample - loss: 983.0537
Epoch 42/200
93/93 [==============================] - 0s 236us/sample - loss: 1011.0364
Epoch 43/200
93/93 [==============================] - 0s 268us/sample - loss: 891.6107
Epoch 44/200
93/93 [==============================] - 0s 300us/sample - loss: 850.1588
Epoch 45/200
93/93 [==============================] - 0s 279us/sample - loss: 863.4702
Epoch 46/200
93/93 [==============================] - 0s 268us/sample - loss: 781.5220
Epoch 47/200
93/93 [==============================] - 0s 247us/sample - loss: 660.5894
Epoch 48/200
93/93 [==============================] - 0s 257us/sample - loss: 627.8770
Epoch 49/200
93/93 [==============================] - 0s 290us/sample - loss: 568.8002
Epoch 50/200
93/93 [==============================] - 0s 257us/sample - loss: 601.5517
Epoch 51/200
93/93 [==============================] - 0s 263us/sample - loss: 577.9770
Epoch 52/200
93/93 [==============================] - 0s 247us/sample - loss: 480.9257
Epoch 53/200
93/93 [==============================] - 0s 279us/sample - loss: 641.0095
Epoch 54/200
93/93 [==============================] - 0s 289us/sample - loss: 544.6537
Epoch 55/200
93/93 [==============================] - 0s 268us/sample - loss: 539.0851
Epoch 56/200
93/93 [==============================] - 0s 279us/sample - loss: 463.1240
Epoch 57/200
93/93 [==============================] - 0s 279us/sample - loss: 431.7946
Epoch 58/200
93/93 [==============================] - 0s 268us/sample - loss: 438.0192
Epoch 59/200
93/93 [==============================] - 0s 257us/sample - loss: 413.8976
Epoch 60/200
93/93 [==============================] - 0s 268us/sample - loss: 391.1696
Epoch 61/200
93/93 [==============================] - 0s 268us/sample - loss: 406.2143
Epoch 62/200
93/93 [==============================] - 0s 294us/sample - loss: 371.4872
Epoch 63/200
93/93 [==============================] - 0s 247us/sample - loss: 392.4871
Epoch 64/200
93/93 [==============================] - 0s 268us/sample - loss: 328.8311
Epoch 65/200
93/93 [==============================] - 0s 257us/sample - loss: 364.6389
Epoch 66/200
93/93 [==============================] - 0s 258us/sample - loss: 399.0587
Epoch 67/200
93/93 [==============================] - 0s 284us/sample - loss: 550.5383
Epoch 68/200
93/93 [==============================] - 0s 290us/sample - loss: 313.0017
Epoch 69/200
93/93 [==============================] - 0s 279us/sample - loss: 448.8452
Epoch 70/200
93/93 [==============================] - 0s 246us/sample - loss: 388.7016
Epoch 71/200
93/93 [==============================] - 0s 255us/sample - loss: 359.1644
Epoch 72/200
93/93 [==============================] - 0s 290us/sample - loss: 506.8867
Epoch 73/200
93/93 [==============================] - 0s 257us/sample - loss: 335.7013
Epoch 74/200
93/93 [==============================] - 0s 246us/sample - loss: 364.6273
Epoch 75/200
93/93 [==============================] - 0s 257us/sample - loss: 301.9216
Epoch 76/200
93/93 [==============================] - 0s 289us/sample - loss: 319.7077
Epoch 77/200
93/93 [==============================] - 0s 279us/sample - loss: 331.6845
Epoch 78/200
93/93 [==============================] - 0s 254us/sample - loss: 251.1727
Epoch 79/200
93/93 [==============================] - 0s 279us/sample - loss: 428.7439
Epoch 80/200
93/93 [==============================] - 0s 257us/sample - loss: 456.2505
Epoch 81/200
93/93 [==============================] - 0s 257us/sample - loss: 631.0843
Epoch 82/200
93/93 [==============================] - 0s 253us/sample - loss: 437.4807
Epoch 83/200
93/93 [==============================] - 0s 246us/sample - loss: 404.3329
Epoch 84/200
93/93 [==============================] - 0s 290us/sample - loss: 383.5194
Epoch 85/200
93/93 [==============================] - 0s 257us/sample - loss: 322.9205
Epoch 86/200
93/93 [==============================] - 0s 269us/sample - loss: 307.1816
Epoch 87/200
93/93 [==============================] - 0s 246us/sample - loss: 330.4061
Epoch 88/200
93/93 [==============================] - 0s 290us/sample - loss: 284.6791
Epoch 89/200
93/93 [==============================] - 0s 268us/sample - loss: 283.1615
Epoch 90/200
93/93 [==============================] - 0s 281us/sample - loss: 260.3463
Epoch 91/200
93/93 [==============================] - 0s 279us/sample - loss: 233.9445
Epoch 92/200
93/93 [==============================] - 0s 268us/sample - loss: 234.7128
Epoch 93/200
93/93 [==============================] - 0s 247us/sample - loss: 241.6277
Epoch 94/200
93/93 [==============================] - 0s 274us/sample - loss: 227.0018
Epoch 95/200
93/93 [==============================] - 0s 268us/sample - loss: 212.3421
Epoch 96/200
93/93 [==============================] - 0s 247us/sample - loss: 222.8575
Epoch 97/200
93/93 [==============================] - 0s 247us/sample - loss: 229.3052

Epoch 98/200
93/93 [==============================] - 0s 274us/sample - loss: 243.6171
Epoch 99/200
93/93 [==============================] - 0s 279us/sample - loss: 158.2373
Epoch 100/200
93/93 [==============================] - 0s 279us/sample - loss: 241.6914
Epoch 101/200
93/93 [==============================] - 0s 246us/sample - loss: 173.1859
Epoch 102/200
93/93 [==============================] - 0s 268us/sample - loss: 192.2440
Epoch 103/200
93/93 [==============================] - 0s 253us/sample - loss: 177.6739
Epoch 104/200
93/93 [==============================] - 0s 268us/sample - loss: 167.5397
Epoch 105/200
93/93 [==============================] - 0s 247us/sample - loss: 150.1210
Epoch 106/200
93/93 [==============================] - 0s 262us/sample - loss: 130.8138
Epoch 107/200
93/93 [==============================] - 0s 268us/sample - loss: 166.5745
Epoch 108/200
93/93 [==============================] - 0s 257us/sample - loss: 193.6013
Epoch 109/200
93/93 [==============================] - 0s 257us/sample - loss: 134.9640
Epoch 110/200
93/93 [==============================] - 0s 247us/sample - loss: 180.0668
Epoch 111/200
93/93 [==============================] - 0s 263us/sample - loss: 152.9999
Epoch 112/200
93/93 [==============================] - 0s 279us/sample - loss: 210.2024
Epoch 113/200
93/93 [==============================] - 0s 246us/sample - loss: 125.6401
Epoch 114/200
93/93 [==============================] - 0s 268us/sample - loss: 358.2384
Epoch 115/200
93/93 [==============================] - 0s 279us/sample - loss: 182.4947
Epoch 116/200
93/93 [==============================] - 0s 279us/sample - loss: 185.3612
Epoch 117/200
93/93 [==============================] - 0s 268us/sample - loss: 154.0710
Epoch 118/200
93/93 [==============================] - 0s 236us/sample - loss: 151.3745
Epoch 119/200
93/93 [==============================] - 0s 268us/sample - loss: 143.3610
Epoch 120/200
93/93 [==============================] - 0s 257us/sample - loss: 129.2871
Epoch 121/200
93/93 [==============================] - 0s 279us/sample - loss: 125.5282
Epoch 122/200
93/93 [==============================] - 0s 257us/sample - loss: 127.0739
Epoch 123/200
93/93 [==============================] - 0s 279us/sample - loss: 113.6358
Epoch 124/200
93/93 [==============================] - 0s 268us/sample - loss: 119.9860
Epoch 125/200
93/93 [==============================] - 0s 258us/sample - loss: 105.0452
Epoch 126/200
93/93 [==============================] - 0s 279us/sample - loss: 112.2692
Epoch 127/200
93/93 [==============================] - 0s 279us/sample - loss: 101.9530
Epoch 128/200
93/93 [==============================] - 0s 257us/sample - loss: 108.6907
Epoch 129/200
93/93 [==============================] - 0s 247us/sample - loss: 100.5878
Epoch 130/200
93/93 [==============================] - 0s 246us/sample - loss: 97.4319
Epoch 131/200
93/93 [==============================] - 0s 268us/sample - loss: 95.0035
Epoch 132/200
93/93 [==============================] - 0s 257us/sample - loss: 93.5164
Epoch 133/200
93/93 [==============================] - 0s 257us/sample - loss: 92.9234
Epoch 134/200
93/93 [==============================] - 0s 279us/sample - loss: 92.9312
Epoch 135/200
93/93 [==============================] - 0s 268us/sample - loss: 90.5849
Epoch 136/200
93/93 [==============================] - 0s 268us/sample - loss: 93.7610
Epoch 137/200
93/93 [==============================] - 0s 311us/sample - loss: 91.5849
Epoch 138/200
93/93 [==============================] - 0s 279us/sample - loss: 91.9563
Epoch 139/200
93/93 [==============================] - 0s 279us/sample - loss: 88.0361
Epoch 140/200
93/93 [==============================] - 0s 279us/sample - loss: 88.7179
Epoch 141/200
93/93 [==============================] - 0s 294us/sample - loss: 88.0769
Epoch 142/200
93/93 [==============================] - 0s 289us/sample - loss: 87.5600
Epoch 143/200
93/93 [==============================] - 0s 246us/sample - loss: 86.8038
Epoch 144/200
93/93 [==============================] - 0s 247us/sample - loss: 85.7732
Epoch 145/200
93/93 [==============================] - 0s 265us/sample - loss: 90.8031
Epoch 146/200
93/93 [==============================] - 0s 300us/sample - loss: 104.8309
Epoch 147/200
93/93 [==============================] - 0s 268us/sample - loss: 91.1192
Epoch 148/200
93/93 [==============================] - 0s 268us/sample - loss: 264.7624
Epoch 149/200
93/93 [==============================] - 0s 257us/sample - loss: 787.9967
Epoch 150/200
93/93 [==============================] - 0s 257us/sample - loss: 730.8326
Epoch 151/200
93/93 [==============================] - 0s 279us/sample - loss: 958.8157
Epoch 152/200
93/93 [==============================] - 0s 247us/sample - loss: 744.5999
Epoch 153/200
93/93 [==============================] - 0s 257us/sample - loss: 648.6084
Epoch 154/200
93/93 [==============================] - 0s 279us/sample - loss: 613.4138
Epoch 155/200
93/93 [==============================] - 0s 278us/sample - loss: 583.2799
Epoch 156/200
93/93 [==============================] - 0s 247us/sample - loss: 419.1117
Epoch 157/200
93/93 [==============================] - 0s 268us/sample - loss: 368.3427
Epoch 158/200
93/93 [==============================] - 0s 257us/sample - loss: 317.4431
Epoch 159/200
93/93 [==============================] - 0s 268us/sample - loss: 326.2195
Epoch 160/200
93/93 [==============================] - 0s 252us/sample - loss: 240.0151
Epoch 161/200
93/93 [==============================] - 0s 258us/sample - loss: 275.2477
Epoch 162/200
93/93 [==============================] - 0s 289us/sample - loss: 268.6182
Epoch 163/200
93/93 [==============================] - 0s 290us/sample - loss: 211.8928
Epoch 164/200
93/93 [==============================] - 0s 257us/sample - loss: 202.1441
Epoch 165/200
93/93 [==============================] - 0s 268us/sample - loss: 164.8280
Epoch 166/200
93/93 [==============================] - 0s 279us/sample - loss: 154.1866
Epoch 167/200
93/93 [==============================] - 0s 257us/sample - loss: 161.4618
Epoch 168/200
93/93 [==============================] - 0s 268us/sample - loss: 152.5117
Epoch 169/200
93/93 [==============================] - 0s 268us/sample - loss: 151.7459
Epoch 170/200
93/93 [==============================] - 0s 268us/sample - loss: 153.2140
Epoch 171/200
93/93 [==============================] - 0s 257us/sample - loss: 145.0368
Epoch 172/200
93/93 [==============================] - 0s 257us/sample - loss: 141.0244
Epoch 173/200
93/93 [==============================] - 0s 279us/sample - loss: 137.5174
Epoch 174/200
93/93 [==============================] - 0s 268us/sample - loss: 135.7132
Epoch 175/200
93/93 [==============================] - 0s 247us/sample - loss: 131.7200
Epoch 176/200
93/93 [==============================] - 0s 268us/sample - loss: 128.7386
Epoch 177/200
93/93 [==============================] - 0s 279us/sample - loss: 126.6318
Epoch 178/200
93/93 [==============================] - 0s 300us/sample - loss: 123.3432
Epoch 179/200
93/93 [==============================] - 0s 258us/sample - loss: 120.1136
Epoch 180/200
93/93 [==============================] - 0s 289us/sample - loss: 120.6076
Epoch 181/200
93/93 [==============================] - 0s 258us/sample - loss: 118.6528
Epoch 182/200
93/93 [==============================] - 0s 268us/sample - loss: 114.8006
Epoch 183/200
93/93 [==============================] - 0s 257us/sample - loss: 114.4825
Epoch 184/200
93/93 [==============================] - 0s 268us/sample - loss: 113.3317
Epoch 185/200
93/93 [==============================] - 0s 279us/sample - loss: 114.5154
Epoch 186/200
93/93 [==============================] - 0s 268us/sample - loss: 112.5353
Epoch 187/200
93/93 [==============================] - 0s 268us/sample - loss: 110.6125
Epoch 188/200
93/93 [==============================] - 0s 247us/sample - loss: 110.0438
Epoch 189/200
93/93 [==============================] - 0s 257us/sample - loss: 107.9501
Epoch 190/200
93/93 [==============================] - 0s 257us/sample - loss: 107.2955
Epoch 191/200
93/93 [==============================] - 0s 279us/sample - loss: 106.7038
Epoch 192/200
93/93 [==============================] - 0s 279us/sample - loss: 105.4531
Epoch 193/200
93/93 [==============================] - 0s 268us/sample - loss: 103.8291
Epoch 194/200
93/93 [==============================] - 0s 268us/sample - loss: 102.9309
Epoch 195/200
93/93 [==============================] - 0s 268us/sample - loss: 102.8149
Epoch 196/200
93/93 [==============================] - 0s 246us/sample - loss: 102.8706
Epoch 197/200
93/93 [==============================] - 0s 257us/sample - loss: 101.6436
Epoch 198/200
93/93 [==============================] - 0s 246us/sample - loss: 100.8774
Epoch 199/200
93/93 [==============================] - 0s 290us/sample - loss: 100.0492
Epoch 200/200
93/93 [==============================] - 0s 279us/sample - loss: 98.8707
UBATUBA-PRUMIRIM-99
Train on 92 samples
Epoch 1/200
92/92 [==============================] - 2s 19ms/sample - loss: 956.1636
Epoch 2/200
92/92 [==============================] - 0s 260us/sample - loss: 922.7619
Epoch 3/200
92/92 [==============================] - 0s 260us/sample - loss: 905.6616
Epoch 4/200
92/92 [==============================] - 0s 238us/sample - loss: 880.7973
Epoch 5/200
92/92 [==============================] - 0s 298us/sample - loss: 871.3230
Epoch 6/200
92/92 [==============================] - 0s 260us/sample - loss: 869.1948
Epoch 7/200
92/92 [==============================] - 0s 298us/sample - loss: 852.6014
Epoch 8/200
92/92 [==============================] - 0s 271us/sample - loss: 837.1930
Epoch 9/200
92/92 [==============================] - 0s 271us/sample - loss: 823.4334
Epoch 10/200
92/92 [==============================] - 0s 293us/sample - loss: 801.9260
Epoch 11/200
92/92 [==============================] - 0s 282us/sample - loss: 782.8341
Epoch 12/200
92/92 [==============================] - 0s 249us/sample - loss: 756.9637
Epoch 13/200
92/92 [==============================] - 0s 273us/sample - loss: 716.9790
Epoch 14/200
92/92 [==============================] - 0s 260us/sample - loss: 684.8195
Epoch 15/200
92/92 [==============================] - 0s 271us/sample - loss: 642.7308
Epoch 16/200
92/92 [==============================] - 0s 282us/sample - loss: 622.9933
Epoch 17/200
92/92 [==============================] - 0s 255us/sample - loss: 565.2821
Epoch 18/200
92/92 [==============================] - 0s 271us/sample - loss: 556.7511
Epoch 19/200
92/92 [==============================] - 0s 282us/sample - loss: 545.2227
Epoch 20/200
92/92 [==============================] - 0s 271us/sample - loss: 538.6357
Epoch 21/200
92/92 [==============================] - 0s 255us/sample - loss: 516.1812
Epoch 22/200
92/92 [==============================] - 0s 271us/sample - loss: 506.2007
Epoch 23/200
92/92 [==============================] - 0s 271us/sample - loss: 504.8299
Epoch 24/200
92/92 [==============================] - 0s 260us/sample - loss: 496.2357
Epoch 25/200
92/92 [==============================] - 0s 271us/sample - loss: 484.0993
Epoch 26/200
92/92 [==============================] - 0s 249us/sample - loss: 470.4318
Epoch 27/200
92/92 [==============================] - 0s 271us/sample - loss: 480.9583
Epoch 28/200
92/92 [==============================] - 0s 260us/sample - loss: 455.3280
Epoch 29/200
92/92 [==============================] - 0s 260us/sample - loss: 456.4690
Epoch 30/200
92/92 [==============================] - 0s 260us/sample - loss: 455.6302
Epoch 31/200
92/92 [==============================] - 0s 271us/sample - loss: 436.7716
Epoch 32/200
92/92 [==============================] - 0s 282us/sample - loss: 442.8986
Epoch 33/200
92/92 [==============================] - 0s 271us/sample - loss: 419.4941
Epoch 34/200
92/92 [==============================] - 0s 249us/sample - loss: 469.6688
Epoch 35/200
92/92 [==============================] - 0s 260us/sample - loss: 415.5535
Epoch 36/200
92/92 [==============================] - 0s 271us/sample - loss: 428.5337
Epoch 37/200
92/92 [==============================] - 0s 260us/sample - loss: 408.1077
Epoch 38/200
92/92 [==============================] - 0s 279us/sample - loss: 422.3512
Epoch 39/200
92/92 [==============================] - 0s 260us/sample - loss: 406.8907
Epoch 40/200
92/92 [==============================] - 0s 271us/sample - loss: 387.3740
Epoch 41/200
92/92 [==============================] - 0s 260us/sample - loss: 386.3002
Epoch 42/200
92/92 [==============================] - 0s 282us/sample - loss: 367.9275
Epoch 43/200
92/92 [==============================] - 0s 260us/sample - loss: 366.7816
Epoch 44/200
92/92 [==============================] - 0s 282us/sample - loss: 368.8793
Epoch 45/200
92/92 [==============================] - 0s 249us/sample - loss: 353.7963
Epoch 46/200
92/92 [==============================] - 0s 260us/sample - loss: 355.1895
Epoch 47/200
92/92 [==============================] - 0s 271us/sample - loss: 357.9696
Epoch 48/200
92/92 [==============================] - 0s 282us/sample - loss: 347.5538
Epoch 49/200
92/92 [==============================] - 0s 282us/sample - loss: 327.2415
Epoch 50/200
92/92 [==============================] - 0s 249us/sample - loss: 349.6115
Epoch 51/200
92/92 [==============================] - 0s 260us/sample - loss: 340.0860
Epoch 52/200
92/92 [==============================] - 0s 265us/sample - loss: 324.2208
Epoch 53/200
92/92 [==============================] - 0s 271us/sample - loss: 354.8673
Epoch 54/200
92/92 [==============================] - 0s 271us/sample - loss: 323.3889
Epoch 55/200
92/92 [==============================] - 0s 260us/sample - loss: 350.8931
Epoch 56/200
92/92 [==============================] - 0s 260us/sample - loss: 310.1447
Epoch 57/200
92/92 [==============================] - 0s 258us/sample - loss: 313.2460
Epoch 58/200
92/92 [==============================] - 0s 260us/sample - loss: 292.0446
Epoch 59/200
92/92 [==============================] - 0s 249us/sample - loss: 283.7644
Epoch 60/200
92/92 [==============================] - 0s 255us/sample - loss: 273.4546
Epoch 61/200
92/92 [==============================] - 0s 260us/sample - loss: 285.7932
Epoch 62/200
92/92 [==============================] - 0s 314us/sample - loss: 294.2987
Epoch 63/200
92/92 [==============================] - 0s 260us/sample - loss: 283.8711
Epoch 64/200
92/92 [==============================] - 0s 260us/sample - loss: 298.7977
Epoch 65/200
92/92 [==============================] - 0s 271us/sample - loss: 254.9058
Epoch 66/200
92/92 [==============================] - 0s 249us/sample - loss: 247.1808
Epoch 67/200
92/92 [==============================] - 0s 293us/sample - loss: 283.0752
Epoch 68/200
92/92 [==============================] - 0s 252us/sample - loss: 237.5319
Epoch 69/200
92/92 [==============================] - 0s 282us/sample - loss: 242.1712
Epoch 70/200
92/92 [==============================] - 0s 255us/sample - loss: 213.3760
Epoch 71/200
92/92 [==============================] - 0s 271us/sample - loss: 214.0813
Epoch 72/200
92/92 [==============================] - 0s 271us/sample - loss: 209.0167
Epoch 73/200
92/92 [==============================] - 0s 260us/sample - loss: 199.3287
Epoch 74/200
92/92 [==============================] - 0s 271us/sample - loss: 191.7926
Epoch 75/200
92/92 [==============================] - 0s 271us/sample - loss: 188.9078
Epoch 76/200
92/92 [==============================] - 0s 260us/sample - loss: 181.7148
Epoch 77/200
92/92 [==============================] - 0s 260us/sample - loss: 173.5176
Epoch 78/200
92/92 [==============================] - 0s 277us/sample - loss: 169.2840
Epoch 79/200
92/92 [==============================] - 0s 282us/sample - loss: 171.8093
Epoch 80/200
92/92 [==============================] - 0s 260us/sample - loss: 178.7483
Epoch 81/200
92/92 [==============================] - 0s 249us/sample - loss: 168.6838
Epoch 82/200
92/92 [==============================] - 0s 249us/sample - loss: 171.1860
Epoch 83/200
92/92 [==============================] - 0s 336us/sample - loss: 163.8545
Epoch 84/200

92/92 [==============================] - 0s 256us/sample - loss: 150.3179
Epoch 85/200
92/92 [==============================] - 0s 260us/sample - loss: 159.4538
Epoch 86/200
92/92 [==============================] - 0s 260us/sample - loss: 141.3843
Epoch 87/200
92/92 [==============================] - 0s 282us/sample - loss: 143.6816
Epoch 88/200
92/92 [==============================] - 0s 239us/sample - loss: 136.7234
Epoch 89/200
92/92 [==============================] - 0s 249us/sample - loss: 133.1735
Epoch 90/200
92/92 [==============================] - 0s 249us/sample - loss: 129.7935
Epoch 91/200
92/92 [==============================] - 0s 282us/sample - loss: 135.2955
Epoch 92/200
92/92 [==============================] - 0s 244us/sample - loss: 126.0153
Epoch 93/200
92/92 [==============================] - 0s 249us/sample - loss: 128.1660
Epoch 94/200
92/92 [==============================] - 0s 271us/sample - loss: 121.0105
Epoch 95/200
92/92 [==============================] - 0s 282us/sample - loss: 117.4995
Epoch 96/200
92/92 [==============================] - 0s 271us/sample - loss: 114.0621
Epoch 97/200
92/92 [==============================] - 0s 303us/sample - loss: 116.7711
Epoch 98/200
92/92 [==============================] - 0s 282us/sample - loss: 116.4570
Epoch 99/200
92/92 [==============================] - 0s 286us/sample - loss: 109.8064
Epoch 100/200
92/92 [==============================] - 0s 238us/sample - loss: 117.7933
Epoch 101/200
92/92 [==============================] - 0s 260us/sample - loss: 125.1844
Epoch 102/200
92/92 [==============================] - 0s 260us/sample - loss: 109.6149
Epoch 103/200
92/92 [==============================] - 0s 271us/sample - loss: 190.1779
Epoch 104/200
92/92 [==============================] - 0s 252us/sample - loss: 208.1408
Epoch 105/200
92/92 [==============================] - 0s 271us/sample - loss: 137.8975
Epoch 106/200
92/92 [==============================] - 0s 271us/sample - loss: 228.6707
Epoch 107/200
92/92 [==============================] - 0s 271us/sample - loss: 181.5300
Epoch 108/200
92/92 [==============================] - 0s 260us/sample - loss: 163.7786
Epoch 109/200
92/92 [==============================] - 0s 260us/sample - loss: 141.1496
Epoch 110/200
92/92 [==============================] - 0s 271us/sample - loss: 140.2002
Epoch 111/200
92/92 [==============================] - 0s 271us/sample - loss: 128.4855
Epoch 112/200
92/92 [==============================] - 0s 282us/sample - loss: 119.4838
Epoch 113/200
92/92 [==============================] - 0s 260us/sample - loss: 114.9327
Epoch 114/200
92/92 [==============================] - 0s 271us/sample - loss: 112.8752
Epoch 115/200
92/92 [==============================] - 0s 260us/sample - loss: 106.4316
Epoch 116/200
92/92 [==============================] - 0s 271us/sample - loss: 106.2426
Epoch 117/200
92/92 [==============================] - 0s 271us/sample - loss: 101.2610
Epoch 118/200
92/92 [==============================] - 0s 271us/sample - loss: 96.5969
Epoch 119/200
92/92 [==============================] - 0s 271us/sample - loss: 96.4266
Epoch 120/200
92/92 [==============================] - 0s 314us/sample - loss: 92.6950
Epoch 121/200
92/92 [==============================] - 0s 271us/sample - loss: 96.6757
Epoch 122/200
92/92 [==============================] - 0s 282us/sample - loss: 92.0734
Epoch 123/200
92/92 [==============================] - 0s 271us/sample - loss: 89.6324
Epoch 124/200
92/92 [==============================] - 0s 260us/sample - loss: 87.9060
Epoch 125/200
92/92 [==============================] - 0s 282us/sample - loss: 89.8867
Epoch 126/200
92/92 [==============================] - 0s 271us/sample - loss: 91.5522
Epoch 127/200
92/92 [==============================] - 0s 271us/sample - loss: 84.9448
Epoch 128/200
92/92 [==============================] - 0s 260us/sample - loss: 108.7729
Epoch 129/200
92/92 [==============================] - 0s 249us/sample - loss: 120.7226
Epoch 130/200
92/92 [==============================] - 0s 293us/sample - loss: 88.6544
Epoch 131/200
92/92 [==============================] - 0s 273us/sample - loss: 219.4934
Epoch 132/200
92/92 [==============================] - 0s 271us/sample - loss: 179.5361
Epoch 133/200
92/92 [==============================] - 0s 282us/sample - loss: 164.8633
Epoch 134/200
92/92 [==============================] - 0s 271us/sample - loss: 131.9751
Epoch 135/200
92/92 [==============================] - 0s 269us/sample - loss: 124.0421
Epoch 136/200
92/92 [==============================] - 0s 282us/sample - loss: 107.0869
Epoch 137/200
92/92 [==============================] - 0s 260us/sample - loss: 108.8896
Epoch 138/200
92/92 [==============================] - 0s 271us/sample - loss: 117.0424
Epoch 139/200
92/92 [==============================] - 0s 271us/sample - loss: 102.5657
Epoch 140/200
92/92 [==============================] - 0s 271us/sample - loss: 94.5638
Epoch 141/200
92/92 [==============================] - 0s 304us/sample - loss: 90.2457
Epoch 142/200
92/92 [==============================] - 0s 249us/sample - loss: 86.5957
Epoch 143/200
92/92 [==============================] - 0s 282us/sample - loss: 85.8625
Epoch 144/200
92/92 [==============================] - 0s 249us/sample - loss: 83.7012
Epoch 145/200
92/92 [==============================] - 0s 304us/sample - loss: 81.0523
Epoch 146/200
92/92 [==============================] - 0s 271us/sample - loss: 78.9745
Epoch 147/200
92/92 [==============================] - 0s 249us/sample - loss: 83.8090
Epoch 148/200
92/92 [==============================] - 0s 260us/sample - loss: 94.9974
Epoch 149/200
92/92 [==============================] - 0s 282us/sample - loss: 78.6764
Epoch 150/200
92/92 [==============================] - 0s 277us/sample - loss: 82.0902
Epoch 151/200
92/92 [==============================] - 0s 271us/sample - loss: 78.7986
Epoch 152/200
92/92 [==============================] - 0s 293us/sample - loss: 75.7890
Epoch 153/200
92/92 [==============================] - 0s 249us/sample - loss: 76.1999
Epoch 154/200
92/92 [==============================] - 0s 270us/sample - loss: 74.8384
Epoch 155/200
92/92 [==============================] - 0s 249us/sample - loss: 74.3817
Epoch 156/200
92/92 [==============================] - 0s 292us/sample - loss: 73.3946
Epoch 157/200
92/92 [==============================] - 0s 282us/sample - loss: 72.7330
Epoch 158/200
92/92 [==============================] - 0s 260us/sample - loss: 72.2097
Epoch 159/200
92/92 [==============================] - 0s 271us/sample - loss: 71.6970
Epoch 160/200
92/92 [==============================] - 0s 259us/sample - loss: 71.3686
Epoch 161/200
92/92 [==============================] - 0s 314us/sample - loss: 71.9306
Epoch 162/200
92/92 [==============================] - 0s 249us/sample - loss: 73.0009
Epoch 163/200
92/92 [==============================] - 0s 250us/sample - loss: 71.2528
Epoch 164/200
92/92 [==============================] - 0s 287us/sample - loss: 69.9873
Epoch 165/200
92/92 [==============================] - 0s 293us/sample - loss: 73.2868
Epoch 166/200
92/92 [==============================] - 0s 282us/sample - loss: 77.6410
Epoch 167/200
92/92 [==============================] - 0s 238us/sample - loss: 82.1946
Epoch 168/200
92/92 [==============================] - 0s 260us/sample - loss: 79.5687
Epoch 169/200
92/92 [==============================] - 0s 271us/sample - loss: 80.3125
Epoch 170/200
92/92 [==============================] - 0s 238us/sample - loss: 89.5060
Epoch 171/200
92/92 [==============================] - 0s 258us/sample - loss: 73.6154
Epoch 172/200
92/92 [==============================] - 0s 249us/sample - loss: 77.3995
Epoch 173/200
92/92 [==============================] - 0s 260us/sample - loss: 74.2857
Epoch 174/200
92/92 [==============================] - 0s 238us/sample - loss: 75.0628
Epoch 175/200
92/92 [==============================] - 0s 282us/sample - loss: 72.9568
Epoch 176/200
92/92 [==============================] - 0s 260us/sample - loss: 71.7863
Epoch 177/200
92/92 [==============================] - 0s 293us/sample - loss: 71.6588

Epoch 178/200
92/92 [==============================] - 0s 260us/sample - loss: 68.7621
Epoch 179/200
92/92 [==============================] - 0s 249us/sample - loss: 76.0328
Epoch 180/200
92/92 [==============================] - 0s 260us/sample - loss: 68.4808
Epoch 181/200
92/92 [==============================] - 0s 271us/sample - loss: 70.9490
Epoch 182/200
92/92 [==============================] - 0s 293us/sample - loss: 69.7648
Epoch 183/200
92/92 [==============================] - 0s 238us/sample - loss: 71.5718
Epoch 184/200
92/92 [==============================] - 0s 260us/sample - loss: 65.9814
Epoch 185/200
92/92 [==============================] - 0s 293us/sample - loss: 64.9280
Epoch 186/200
92/92 [==============================] - 0s 271us/sample - loss: 64.2950
Epoch 187/200
92/92 [==============================] - 0s 260us/sample - loss: 62.8287
Epoch 188/200
92/92 [==============================] - 0s 282us/sample - loss: 62.3408
Epoch 189/200
92/92 [==============================] - 0s 260us/sample - loss: 61.6907
Epoch 190/200
92/92 [==============================] - 0s 271us/sample - loss: 61.1815
Epoch 191/200
92/92 [==============================] - 0s 249us/sample - loss: 60.7191
Epoch 192/200
92/92 [==============================] - 0s 250us/sample - loss: 60.0412
Epoch 193/200
92/92 [==============================] - 0s 260us/sample - loss: 61.1752
Epoch 194/200
92/92 [==============================] - 0s 271us/sample - loss: 59.6561
Epoch 195/200
92/92 [==============================] - 0s 260us/sample - loss: 58.2982
Epoch 196/200
92/92 [==============================] - 0s 260us/sample - loss: 63.2432
Epoch 197/200
92/92 [==============================] - 0s 282us/sample - loss: 62.1065
Epoch 198/200
92/92 [==============================] - 0s 271us/sample - loss: 70.5540
Epoch 199/200
92/92 [==============================] - 0s 249us/sample - loss: 63.0115
Epoch 200/200
92/92 [==============================] - 0s 325us/sample - loss: 68.0730
UBATUBA-PULSO-68